### ISSUE TITLE
E_NOTICE when checking out

### ISSUE THREAD

**Issue by studio575** [mollie/OpenCart#102]
When I check out i get the following notice:

`Notice: Undefined property: stdClass::$normal in /home/keybag/public_html/catalog/model/extension/payment/mollie/base.php on line 98Notice: Undefined property: stdClass::$normal in /home/keybag/public_html/catalog/model/extension/payment/mollie/base.php on line 98`

I can still proceed the checkout process without any problems.. any idea on how I can fix the error?

**Comment by QualityWorks-Dev** [comment]
we updated the files, please download and install it again. should be fixed


With kind regards / met vriendelijke groet,

Taco van Sambeek



Wold 13 50
8225BZ Lelystad

Tel: (+31) (0)85 7430150
Mob: (+31) (0)6 24608002

Skype: t.van.sambeek

2018-07-24 15:44 GMT+02:00 studio575 <notifications@github.com>:

**Comment by studio575** [comment]
Update files fixed the issue, thanks!
