### ISSUE TITLE
Bancontact not showing

### ISSUE THREAD

**Issue by gh00per** [mollie/OpenCart#105]
Hey,

I enabled Bancontact in Mollie dashboard and also on my webshop. But the payment option isn't visible when I want to pay for my goods. Paypal and iDeal options are visible though.

What's wrong?

Kind regards,

Nick

**Comment by youri13pixels** [comment]
I think there is an issue with api.mollie.nl. All my payment options are disabled. 

> Communicating with Mollie failed:
> Unable to communicate with Mollie (60): The certificate was signed using a signature algorithm that is disabled because it is not secure..
> 
> Please check the following conditions. You can ask your hosting provider to help with this.
> Make sure outside connections to https://api.mollie.nl are not blocked.
> Make sure SSL v3 is disabled on your server. Mollie does not support SSL v3.
> Make sure your server is up-to-date and the latest security patches have been installed.
> 
> Contact info@mollie.nl if this still does not fix your problem.
> Invalid API key!

**Comment by gh00per** [comment]
Hey @youri13pixels  I had the same problem today. Try to update your extension with newest version of Mollie API, solved it for me! Don't forget to refresh modification cache.

**Comment by gh00per** [comment]
Notice: Undefined index: name_mollie_mistercash in /home/rstrading/domains/rstrading.nl/public_html/development/admin/language/en-gb/extension/payment/mollie_mistercash.php on line 4Notice: Undefined index: name_mollie_mistercash in /home/rstrading/domains/rstrading.nl/public_html/development/admin/language/nl-nl/extension/payment/mollie_mistercash.php on line 4
