### ISSUE TITLE
Feature request; Payment links

### ISSUE THREAD

**Issue by nosite** [mollie/OpenCart#11]
Hi,
Maybe a good idea; when a order is made manual by the admin it would me nice to send a payment link by email to the client direct from the dashboard.

**Comment by lurkingrobbert** [comment]
Hi nosite, sorry for the late reply. Thank you for your feature idea. We do not have resources available at this time to add this feature, but have added your feature request to our internal issue tracker.

If you need the feature soon, feel free to add it to our code base and submit a pull request through GitHub.
