### ISSUE TITLE
Mistercash PHP Error after installing via Extension Installer (OC 3.0.2)

### ISSUE THREAD

**Issue by Thylbert** [mollie/OpenCart#110]
Hello!

I've downloaded the 'mollie-opencart-2.3-and-up.ocmod.zip' file and in the OpenCart 3.0.2 I used the Extension Installer to install the ocmod.zip file. 

Installation succesfull! Yay.

Than I went to Extensions > Extensions > Payments and got on top of the page the following 'Notice'

Notice: Undefined index: name_mollie_mistercash in /customers/0/d/4/thylbert.be/httpd.www/webshop/admin/language/en-gb/extension/payment/mollie_mistercash.php on line 4Notice: Undefined index: name_mollie_mistercash in /customers/0/d/4/thylbert.be/httpd.www/webshop/admin/language/en-gb/extension/payment/mollie_mistercash.php on line 4

PS: Is there no extension available for OC 3.0.2? Perhaps the mismatch in version is one of the possible if not the main culprit?

EDIT: Just read the 'and-up' in the name of the file. Nevermind about the post scriptum.

With most kind regards
Thylbert

**Comment by QualityWorks-Dev** [comment]
hello,

This is due to the new version that has Mistercash renamed to Bancontact

Please try to uninstall and reinstall the payment methods

This version is correct for 3.x

With kind regards / met vriendelijke groet,

Taco van Sambeek



Wold 13 50
8225BZ Lelystad

Tel: (+31) (0)85 7430150
Mob: (+31) (0)6 24608002

Skype: t.van.sambeek


Op di 23 okt. 2018 om 10:54 schreef Thylbert <notifications@github.com>:

**Comment by Thylbert** [comment]
Hello Taco

De plugin werkt - voor zover ik kan zien - prima. Met een 'reinstall the payment methods' bedoel je dan de volledige plugin er van pleuren en opnieuw uploaden. Of de eigenlijke payment methods één voor uninstallen/installen.

Ik vermoed het laatste, maar wou toch even dubbelchecken.

Met vriendelijke groet
Thylbert

PS: Blijkt dat ik bij het lezen van je naam automatisch naar Nederlands ben overgeschakeld. Mijn excuses.

**Comment by QualityWorks-Dev** [comment]
Geen probleem, ik ben gewoon Nederlands.

Ik bedoelde gewoon het laatste inderdaad (alles gaat in 1 keer)

Op di 23 okt. 2018 11:15 schreef Thylbert <notifications@github.com>:
