### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by gh00per** [mollie/OpenCart#113]
Hallo,

Wij krijgen onderstaande error bij versie 8.4.1. Bij de nieuwste versie krijgen wij een andere error, dat de bedragen niet matchen - wij denken dat dan BTW van verzendkosten niet meegenomen wordt. Vandaar dat wij nu deze versie gebruiken, maar werkt sinds gisteren ook niet goed.. Het gekke is dat we dit specifieke probleem tijdelijk oplossen door uit te loggen en in te loggen, vervolgens kunnen we wel gewoon betalen.

_Er is een fout opgetreden bij het opzetten van de betaling bij Mollie. Klik op onderstaande knop om terug te keren naar het afrekenscherm.

Error executing API call (422: Unprocessable Entity): The 'streetAndNumber' field should be of type string. Field: billingAddress.streetAndNumber. Documentation: https://docs.mollie.com/reference/v2/payments-api/create-payment_

**Comment by tacovansambeek** [comment]
Dit zou in 9.0.3 allemaal niet voor moeten komen
