### ISSUE TITLE
Error streetAndNumber

### ISSUE THREAD

**Issue by gh00per** [mollie/OpenCart#115]
Krijg onderstaande error wanneer ik product in winkelwagen heb en langer dan 10 min wacht met afrekenen. Als ik uitlog en weer inlog werkt het weer. Ik weet zeker dat mijn klanten hier ook last van hebben dus wil het graag oplossen.

--------

_Er is een fout opgetreden bij het opzetten van de betaling bij Mollie. Klik op onderstaande knop om terug te keren naar het afrekenscherm.

Error executing API call (422: Unprocessable Entity): The 'streetAndNumber' field should be of type string. Field: billingAddress.streetAndNumber. Documentation: https://docs.mollie.com/reference/v2/payments-api/create-payment_

**Comment by tacovansambeek** [comment]
is dit nog actueel? kan je dan eventueel de info geven die met de order meegezonden wordt? dus adres gegevens enzo?

**Comment by gh00per** [comment]
Ik ben teruggegaan naar een oudere versie, aangezien dit probleem bleef aanhouden en zeer willekeurig was. Klanten konden hierdoor niet afrekenen etc. Maar ik denk als ik terug ga naar de nieuw(ste) versie, dit inderdaad nog actueel is.
