### ISSUE TITLE
Fatal error: Uncaught exception 'Mollie\Api\Exceptions\ApiException' with message 'Error executing API call (400: Bad Request): 

### ISSUE THREAD

**Issue by gjsn** [mollie/OpenCart#116]
Goedemiddag,
Ik ben met een update bezig van 2.0.1.1. naar 3.0.20. 
Eerst mollie van mp opencart geïnstalleerd, kreeg diverse foutmeldingen. Alles eruit gehaald en mollie-opencart-1.5-and-up.vqmod erin geplaatst. Bij het afrekenproces krijg ik de volgende melding. 

Fatal error: Uncaught exception 'Mollie\Api\Exceptions\ApiException' with message 'Error executing API call (400: Bad Request): The amount is lower than the minimum. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors' in /home/****/****/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php:391 Stack trace: #0 /home/****/****/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(360): Mollie\Api\MollieApiClient->parseResponseBody(Object(_PhpScoper5bbb1f4b001f3\GuzzleHttp\Psr7\Response)) #1 /home/****/****/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(321): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) #2 /home/****/****/catalog/controller/payment/mollie-api-client/src/Endpoints/EndpointAbstract.php(118): Mollie\Api\MollieApiClient->performHttpCall('GET', 'methods?amo in /home/****/****/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php on line 391

Ben erg benieuwd hoe ik dit op kan lossen.
Hoor het graag

**Comment by gjsn** [comment]
Niemand een idee of tips?

**Comment by tacovansambeek** [comment]
is dit probleem ook bij 9.x nog actueel?
