### ISSUE TITLE
Error: API call (422: Unprocessable Entity) Amount

### ISSUE THREAD

**Issue by stuiterbal1984** [mollie/OpenCart#119]
Hoi!

Ik krijg de volgende melding. Opencart 3.0.2.0

Er is een fout opgetreden bij het opzetten van de betaling bij Mollie. Klik op onderstaande knop om terug te keren naar het afrekenscherm.

Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be $10.05 but got $2.55. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors

**Comment by thanuzz** [comment]
Ik heb dezelfde melding. Om precies te zijn:
```Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €2.75 but got €3.75. Field: amount. 
```
Dit wordt waarschijnlijk veroorzaakt door een 'order total' module, die wel in het totaal wordt meegerekend maar niet in de optelsom die Mollie klaarblijkelijk nog doet. In mijn geval betreft het de Module [X-Fee](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=13535) die ik heb ingesteld om een toeslag van een euro bij het totaal op te tellen als de gekozen Mollie betaalmethode Klarna, PayPal of Bancontact is. Dit werkt overigens goed bij het besteloverzicht in de checkout maar dus niet als je daadwerkelijk je bestelling wilt plaatsen.

Iemand enig idee waar dit zit en hoe dit op te lossen?

**Comment by QualityWorks** [comment]
we zijn bezig met een update waarin dit opgelost wordt.

**Comment by TiaID** [comment]
Is er enig idee wanneer de update er zou zijn? Wil graag klarna aanbieden weer, maar nu kan dat nog niet.

**Comment by PhoenixInteractiveNL** [comment]
Wij hebben hetzelfde probleem, wij gebruiken de LOW ORDER FEE (voor kleine bestellingen) eenmaal geactiveerd krijgen wij de foutmelding:

Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €0.90 but got €2.65. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors

Dit heeft wel goed gewerkt in v8.4.2

**Comment by tacovansambeek** [comment]
dit zou nu opgelost moeten zijn in de laatste versie
