### ISSUE TITLE
iso_code_2 undefined index

### ISSUE THREAD

**Issue by Wetronic** [mollie/OpenCart#121]
Sinds een paar dagen is mollie er in ene mee gestopt met deze meldingen als gevolg:

Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82Notice: Undefined index: iso_code_2 in /home/wetronic/wetronic.nl/catalog/model/payment/mollie/base.php on line 82

Herinstalleren en alles is geprobeerd maar werkt helaas niet, op dit moment kunnen er door deze foutmelding geen betalingen worden gedaan dat is natuurlijk erg vervelend. 

Ik zag hier al een eerdere melding van 3 weken geleden voorbij komen met dezelfde foutmelding maar helaas daar nog geen antwoord op. Hopelijk komt hier wel antwoord op want een webshop waar je niet kan betalen heeft geen lang leven..

**Comment by tacovansambeek** [comment]
This has been fixed in 9.0.2
