### ISSUE TITLE
9.0.2. problem

### ISSUE THREAD

**Issue by gh00per** [mollie/OpenCart#126]
Hello,

After installing 9.0.2. I have a problem. The payment methods do not show up in checkout page. And sometimes it automatically removes my live API key.

**Comment by youri13pixels** [comment]
I have the same issue that API is gonne sometimes and don't allow to update payment Status. Also Payment status "do not update status (not recommended )" isn't working properly. When selected it jumps back to default.

**Comment by tacovansambeek** [comment]
we have a fix ready for this for 9.0.3

**Comment by youri13pixels** [comment]
Perfect! When will it be available?

**Comment by QualityWorks** [comment]
soon. I don't have an exact date yet

**Comment by youri13pixels** [comment]
Hey Taco, any updates on 9,0,3?
