### ISSUE TITLE
Mollie permissions issue

### ISSUE THREAD

**Issue by beireken** [mollie/OpenCart#127]
On a new install of opencart 3.0.20 and mollie 9.0.2 i get the following errors on the top of my mollie payment method selection menu.

`Warning: unlink(/var/www/html/opencart/admin/view/template/extension/payment/mollie(max_1.5.6.4).tpl): Permission denied in /var/www/html/opencart/admin/controller/payment/mollie/base.php on line 182Warning: unlink(/var/www/html/opencart/admin/view/template/payment/mollie(max_1.5.6.4).tpl): Permission denied in /var/www/html/opencart/admin/controller/payment/mollie/base.php on line 183Warning: unlink(/var/www/html/opencart/catalog/view/theme/default/template/extension/payment/mollie_return.tpl): Permission denied in /var/www/html/opencart/admin/controller/payment/mollie/base.php on line 184Warning: unlink(/var/www/html/opencart/catalog/view/theme/default/template/payment/mollie_return.tpl): No such file or directory in /var/www/html/opencart/admin/controller/payment/mollie/base.php on line 185Warning: unlink(/var/www/html/opencart/catalog/view/theme/default/template/extension/payment/mollie_checkout_form.tpl): Permission denied in /var/www/html/opencart/admin/controller/payment/mollie/base.php on line 186Warning: unlink(/var/www/html/opencart/catalog/view/theme/default/template/payment/mollie_checkout_form.tpl): No such file or directory in /var/www/html/opencart/admin/controller/payment/mollie/base.php on line 187`

Is this a file permissions issue? I copied all files through ftp to the opencart folder from the ZIP file.

**Comment by tacovansambeek** [comment]
this is a file permission issue.
