### ISSUE TITLE
9.0.2: Undefined index: name_mollie_mistercash 

### ISSUE THREAD

**Issue by thanuzz** [mollie/OpenCart#128]
Na de installatie van 9.0.2 krijg ik in OpenCart de volgende error te zien:

```
Notice: Undefined index: name_mollie_mistercash in /home/pcxj323337/domains/leukvanmij.nl/public_html/admin/language/english/payment/mollie_mistercash.php on line 4
Notice: Undefined index: name_mollie_mistercash in /home/pcxj323337/domains/leukvanmij.nl/public_html/admin/language/en-gb/payment/mollie_mistercash.php on line 4
Notice: Undefined index: name_mollie_mistercash in /home/pcxj323337/domains/leukvanmij.nl/public_html/admin/language/nl-nl/payment/mollie_mistercash.php on line 4
```

Ik heb de Mollie module al gedeinstalleerd en opnieuw geinstalleerd, de files proberen opnieuw te uploaden en cache geleegd maar dit helpt niet.
Opencart versie 2.3.0.2

Is er een snelle fix die ik kan doen om dit op te lossen?
Alvast bedankt.

**Comment by tacovansambeek** [comment]
Er zit een cleanup functie in de module waar nog een kleine bug in zat. als je update naar 9.0.3 zou dit weg moeten zijn
