### ISSUE TITLE
9.0.2: Betalen niet meer mogelijk, 500 error bij alle betaalmethodes

### ISSUE THREAD

**Issue by thanuzz** [mollie/OpenCart#129]
Na installatie 9.0.2: Na keuze betaalmethode en bevestiging bestelling, krijgen alle bezoekers bij alle betaalmethodes een HTTP ERROR 500 pagina te zien....

```
Request URL: https://www.leukvanmij.nl/index.php?route=payment/mollie_ideal/payment
Request Method: POST
Status Code: 500 Internal Server Error
```
Error-log in opencart heeft geen logs hiervan...
Opencart versie 2.3.0.2

Ga voor nu terug na 9.0.0 nu.

**Comment by tacovansambeek** [comment]
Heb je hier bij 9.0.3 nog steeds last van?

**Comment by thanuzz** [comment]
Nee, dit lijkt opgelost. Dankjewel en sorry voor de late reactie.
