### ISSUE TITLE
Error: API call (422: Unprocessable Entity) Amount, after install dutch language pack

### ISSUE THREAD

**Issue by inekestijnman** [mollie/OpenCart#130]
I installed ocmod 8.4.2 on a standard opencart 2.2.0.0 installattion. It worked fine,

after installing the dutch language pack Nederlands - Dutch OC 2.x  i get the error
Error executing API call (422: Unprocessable Entity): The amount contains an invalid value. Field: amount.value.

If i check the releases this should have been fixed in the previous version. Can someone direct me to the details of that fix so I can try apply with the dutch pack installed / help with a fix
thanks

**Comment by tacovansambeek** [comment]
This should all be fixed in the latest module. Please install version 9.0.3
