### ISSUE TITLE
Order payment status issue 9.0.3

### ISSUE THREAD

**Issue by youri13pixels** [mollie/OpenCart#134]
After installing 9.0.3. I have a problem. The payment methods do not show up in checkout page. And sometimes it automatically removes my live API key.

I have the same issue that API is gonne sometimes and don't allow to update payment Status. Also Payment status "do not update status (not recommended )" isn't working properly. When selected it jumps back to default. Using Version 3.0.2.0 and mollie 9.0.3

**Comment by youri13pixels** [comment]
When I remove the API Key all are being saved correctly. Problem is on both the test and live api.

**Comment by QualityWorks** [comment]
Is this still an issue on 9.1.0 ?
