### ISSUE TITLE
Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. The 'quantity' field should be a whole number. Field: lines.1.quantity.

### ISSUE THREAD

**Issue by deriise** [mollie/OpenCart#138]
Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. The 'quantity' field should be a whole number. Field: lines.1.quantity.

I get this message because i'm trying to sell half products (example: 0,55 meters of fabric). Is there a way around this?

**Comment by QualityWorks** [comment]
This has been fixed in the latest release
