### ISSUE TITLE
Error for orders >= EUR 1000 : Error executing API call (422: Unprocessable Entity): The amount contains an invalid value. Field: amount.value. Documentation: https://docs.mollie.com/guides/handling-errors

### ISSUE THREAD

**Issue by gdegraaf** [mollie/OpenCart#139]
When trying to pay an order >= 1000 an error is generated: 

> Error executing API call (422: Unprocessable Entity): The amount contains an invalid value. Field: amount.value. Documentation: https://docs.mollie.com/guides/handling-errors

I can see in the release notes this is already fixed for USD, but apparently not for EUR. Is this fixed in an upcoming release and does a workaround exist?

**Comment by gdegraaf** [comment]
Closed, the cause of this issue is not a code error, but a folder structure error

**Comment by Israel-Dev** [comment]
I am dealing with the same situation, could you please explain better what is the issue and how you solved it?

**Comment by gdegraaf** [comment]
@Israel-Dev it's been quite a while ago, so I don't remember exactly. But some folders of the Mollie extension were not placed in the correct (or neccessary) location in the OC folder structure.
