### ISSUE TITLE
return str_replace

### ISSUE THREAD

**Issue by takeoffx** [mollie/OpenCart#14]
I hope to receive some information here on the following subject:

calling this function:

protected function getAdminDirectory()
{
    return str_replace(HTTP_SERVER, '', HTTP_ADMIN);
}
ends in this php statement:

PHP Notice: Use of undefined constant HTTP_ADMIN - assumed 'HTTP_ADMIN' in /xx/xxx/xxx/www/catalog/controller/payment/mollie_ideal.php on line 452

This statements seems to retrieve the admin directory but the constant is undefined, I'm uncertain on where to define it there for my question would be if I could make this static since the directory is known.

If so how would it look like?

{
    return str_replace(HTTP_SERVER, 'admin', admin);
}
Using opencart 2.0.1.1 and Mollie version 5.2.6 https://github.com/mollie/OpenCart/releases

Thank you in advanced.

**Comment by takeoffx** [comment]
Notice: Use of undefined constant HTTP_ADMIN - assumed 'HTTP_ADMIN' in /is/htdocs/xxx/www/catalog/controller/payment/mollie_ideal.php on line 452Warning: Cannot modify header information - headers already sent by (output started at /is/htdocs/xxx/www/index.php:102) in /is/htdocs/xxx/www/system/library/response.php on line 12

**Comment by lvgunst** [comment]
Thanks for reporting this issue. Our module developer has created a fix which you can find in #15
