### ISSUE TITLE
Different folder structure in release 9.x

### ISSUE THREAD

**Issue by gdegraaf** [mollie/OpenCart#140]
Hi, when upgrading from release 8.x to 9.x I found that release 9.x uses a different folder structure.
For example the path to base.php:

8.4.0 = catalog/controller/extension/payment/mollie/base.php
9.0.5 = catalog/controller/payment/mollie/base.php

Effectively this means that people updating to version 9 won't see all changes having effect because the old base.php is still used. So there should be instructions added on how to update from 8.x (or older) to 9.x.

**Comment by QualityWorks** [comment]
there is a cleanup function that should take care of this. This is also used to remove unused files for old payment methods, etc. We'll triple check for this specific case.

**Comment by gdegraaf** [comment]
@QualityWorks is the cleanup function available in both the Opencart Marketplace download (which is an ocmod) and the Github Releases page (https://github.com/mollie/OpenCart/releases)

**Comment by gdegraaf** [comment]
@QualityWorks  I just installed 9.1.11 on a testing environment but this does not clean up the old folder structure.

**Comment by QualityWorks** [comment]
The cleanup function is not included in the installer (marketplace ocmod) as it uses some function from the full version, but ofcourse, if you use the installer to download the full version, Cleanup will be ran from there.
I have doublechecked, the cleanup includes the old folder structure. 
Can you contact me on info@qualityworks.eu so we can have a look together?
