### ISSUE TITLE
Error executing API call (422: Unprocessable Entity)

### ISSUE THREAD

**Issue by TiaID** [mollie/OpenCart#143]
Bij betalen melding:

Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. VAT amount is off. Expected VAT amount to be €5.41 (€31.20 × (21.00% / 121.00%)), got €5.42. Field: lines.1.vatAmount. Documentation: https://docs.mollie.com/guides/handling-errors

Niet bij alle producten.

Mo;llie versie 9.0.5

**Comment by mtothed** [comment]
check your order in extensions kassa? module, taxes should be after sub total
https://forum.opencart.com/viewtopic.php?t=110923

**Comment by TiaID** [comment]
It is enabled and on the right place at checkout.

And it is not at every product/order that you get this error.


Op 2 mei 2019 21:15, om 21:15, mtothed <notifications@github.com> schreef:

**Comment by mjhajdu** [comment]
They really need to fix this. The older API was much better. You simply lose a lot of money when people get this error. What a shame that Mollie cannot properly fix this.

**Comment by QualityWorks** [comment]
we are testing a fix for this

**Comment by Reza-Pasdari** [comment]
Has this issue been fixed?

**Comment by mtothed** [comment]
No

Reza-Pasdari <notifications@github.com> schrieb am Di., 18. Juni 2019,
12:19:

**Comment by QualityWorks** [comment]
We have a beta release ready that should fix this. However, we need to thoroughly test it. If you are willing to help test, it would really help us a lot. please contact us on support.mollie@qualityworks.eu ?

**Comment by QualityWorks** [comment]
we have releasd the 9.1.0 that should fix this
