### ISSUE TITLE
Error: This extension requires VQMod.

### ISSUE THREAD

**Issue by charleyvtl88** [mollie/OpenCart#144]
Hi all,

When installing this extension I get several errors..

First: Fatal error: there's something wrong in header.tpl (comercia/util). When I quote that out, everything works, but then:

This extension requires VQMod. Please download and install it on your shop. You can find the latest release here! But it's using OCMod.

The system is using Muijshop 3.0.4 which is using OpenCart 2 in it. Normally every OpenCart 2 modification works, but this one not.

Does someone know what's going wrong?

**Comment by QualityWorks** [comment]
you need to install vQmod for this extension to work https://github.com/vqmod/vqmod/releases
