### ISSUE TITLE
Cadeaubonnen in checkout geven een 422 error

### ISSUE THREAD

**Issue by Designbase** [mollie/OpenCart#145]
Er is een fout opgetreden bij het opzetten van de betaling bij Mollie. Klik op onderstaande knop om terug te keren naar het afrekenscherm.
Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €11.64 but got €21.64. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors

Het verschil is een Cadeaubon van €10,- die niet meegnomen wordt naar Mollie.

Kan dit gefixed worden? Versie Mollie Opencart 9.0.5

**Comment by QualityWorks** [comment]
ja, we zijn de laatste hand aan het leggen op de volgende versie waar dit in opgelost is

**Comment by Designbase** [comment]
Ok top...

**Comment by Designbase** [comment]
Enig idee wanneer dit gefixed is?

**Comment by QualityWorks** [comment]
We hebben een beta versie klaar, alleen moet eea nog goed doorgetest worden. Mocht je interesse hebben om te helpen testen, kan je dan contact opnemen met support.mollie@qualityworks.eu ?
