### ISSUE TITLE
Fatal error: Class 'comercia\util' not found in ...

### ISSUE THREAD

**Issue by charleyvtl88** [mollie/OpenCart#146]
When I try to install the Mollie payment plugin I get the following error:

Fatal error: Class 'comercia\util' not found in /home/statenhofpers/public_html/components/com_mijoshop/opencart/system/modification/admin/view/template/common/header.tpl on line 4

How can we solve this?

**Comment by QualityWorks** [comment]
This usually means that VQMOD is not installed
