### ISSUE TITLE
Mollie.log: Could not find mollie reference order id

### ISSUE THREAD

**Issue by MadMcJack** [mollie/OpenCart#147]
I am seeing these messages in the Mollie.log
```
Could not find mollie reference order id
Could not find mollie reference order id
Could not find mollie reference order id
```

They seem to originate from when a customer places an order but does not use Mollie as the payment method. 

Can you or I somehow prevent this message from filling the Mollie.log?

It would also be nice if you added a column in the Mollie.log with an indication of the severity of the message, eg:
INFO
WARN
ERROR

Using Opencart 3.0.3.1 with Ajax Quick Checkout and Mollie 9.0.5

**Comment by QualityWorks** [comment]
at the moment, this is not possible. It is a good suggestion for us to work on in the future
