### ISSUE TITLE
Opencart 3.0.2.0

### ISSUE THREAD

**Issue by jlsjonas** [mollie/OpenCart#148]
Opencart 3.0 has been released for over 2 years now, I think it's time to implement support for it...

**Comment by QualityWorks-Dev** [comment]
There has been support for 3.x since Mollie plugin version 8.x

Op za 22 jun. 2019 09:33 schreef Jonas De Kegel <notifications@github.com>:

**Comment by jlsjonas** [comment]
I got that indication a minute ago when coming here via https://www.mollie.com/en/developers/packages
However, the package description is indicating "for OpenCart 1.5.6+ and OpenCart 2.0+." implying 3.0 isn't compatible.
