### ISSUE TITLE
Pricing mismatch in api call? (422)

### ISSUE THREAD

**Issue by jlsjonas** [mollie/OpenCart#149]
Running OC 3.0.2.0 with the latest plugin (installed today)
(using test api key)
For a given order
![image](https://user-images.githubusercontent.com/932193/59961776-911fb100-94dc-11e9-91b2-88635ba457f8.png)

I'm getting the following error, which doesn't add up no matter how you look at it:
An error occurred when setting up the payment with Mollie. Click the button below to return to the checkout page.

`Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €43.28 but got €45.38. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors`

**Comment by jlsjonas** [comment]
To clarify: opencart is calculating taxes for everything including shipping (as it should be, as far as I'm aware) while the mollie plugin seems to be calculating taxes without the shipping fee

**Comment by QualityWorks** [comment]
we have a new version we think should solve all known bugs. would you be happy to try this one? can you please email us on info@qualityworks.eu if you do, so I can send it to you?

**Comment by dhuitin** [comment]
> To clarify: opencart is calculating taxes for everything including shipping (as it should be, as far as I'm aware) while the mollie plugin seems to be calculating taxes without the shipping fee

In case it is not fixed yet: 

https://github.com/mollie/OpenCart/pull/141/files

This change fixed it for me (edit line #280in  catalog/controller/payment/mollie/base.php to `$costWithTax = $this->tax->calculate($cost, $taxClass, $vatRate);`

**Comment by QualityWorks** [comment]
this should be fixed in the current release (9.0.6)
