### ISSUE TITLE
mollie_ideal_status = 1 gebruiken ipv mollie_ideal_status = on

### ISSUE THREAD

**Issue by dhuitin** [mollie/OpenCart#151]
Mollie gebruikt de value "on" om in de sql database (oc_setting) aan te geven of de betaalmethode enabled / disabled is. 

Andere betaalmethoden gebruiken hiervoor de waarde 1 (voor on) of 0 (voor uit) 

Bij extensies die kijken of/welke betaalmethodes enabled zijn gaat dit dus niet goed 

Is het mogelijk om hier ook 1 of 0 voor te gebruiken?

**Comment by QualityWorks** [comment]
goede vondst, we zullen het in de volgende release aanpassen
