### ISSUE TITLE
Blank callback page

### ISSUE THREAD

**Issue by basz** [mollie/OpenCart#152]
After a (test) payment the user is redirected to `index.php?route=payment/mollie_ideal/callback&order_id=13`

However that page is blank and no order with id 13 exists in the opencast database.

The mollie log does show a successful entry

```
2019-07-23 12:03:18 - Order created : mollie_order_id - ord_jpt0fy
2019-07-23 12:03:23 - Received callback for order 13
```

This is on a new opencast installation, with only the Mollie extension (and dependencies) active.

Any pointers would be appreciated.

**Comment by QualityWorks** [comment]
can you please email us on info@qualityworks.eu with the shop url, opencart version and mollie version? we will have a look. also, can you please add the apache error log?

**Comment by basz** [comment]
Hmm. apache logs tells me smtp config was wrong (missed `tls://`). Now it works... Sorry.
