### ISSUE TITLE
comercia_util.xml is causing site to slow down

### ISSUE THREAD

**Issue by Designbase** [mollie/OpenCart#153]
This VQMOD file comercia_util.xml causing big issues with slowing the site down.
Can this be fixed or removed all together?

The webshop is not workable with this activated

**Comment by MadMcJack** [comment]
Try deleting checked.cache and mods.cache in the vqmod directory and see if that helps...

If so...

It is a known issue with vqmod. Sadly opencart admins just ignore the issue. See:
`https://github.com/opencart/opencart/issues/7457`

It would be nice if Mollie also made a native opencart mod without dependency on vqmod so we can just uninstall vqmod altogether.

**Comment by QualityWorks** [comment]
ah yes, I remember this. it can be fixed if you do NOT move the storage folder outside of the public_html folder. the checked.cache won't inflate so much.

On a native module. the issue is that we would have to support 4 versions (1.5, 2.0 - 2.2, 2.3, 3.x)

**Comment by Designbase** [comment]
Looks like it has been solved with the latest 9.0.6 version...
