### ISSUE TITLE
Mollie Klarna Pay Later

### ISSUE THREAD

**Issue by mtothed** [mollie/OpenCart#154]
Problem still occurs with version 9.0.6
Paypal payment is working 
Klarna Pay Later is still not working with the following response from the API

>Error setting up transaction with Mollie: Error executing API call (422: Unprocessable Entity): The method is not available for this payment. Field: payment.method. 

Can this be fixed or explained?
Seems like it is not using the correct Mollie API to create the order, see note in 
https://docs.mollie.com/reference/v2/payments-api/create-payment

> Note
> 
> If you are looking to create payments with the Klarna Pay later or Klarna Slice it payment methods, please use the Create Order API instead.
>

**Comment by QualityWorks** [comment]
we do use the order API. 
can you give a bit more info on the order itself? total amount, country, currency?
Perhaps Mollie can comment on why it was rejected. 

We did build a check that shouldn't show the payment option if it is not available, so I'd also like to find out what is going wrong here.

**Comment by mtothed** [comment]
happens with every amount, 
country: germany
currency: €

**Comment by mtothed** [comment]
Hello again, 
is there any progress or anything else needed? Or any proposals how we can go along to fix the problem? 
Thanks so far

**Comment by QualityWorks** [comment]
can you see if this problem still exists on the 9.1.0 version?

**Comment by QualityWorks** [comment]
I will close this for now, please re-open a new issue if the problem still exists
