### ISSUE TITLE
Please add to faq how to properly update mollie

### ISSUE THREAD

**Issue by ibotu** [mollie/OpenCart#157]
Mollie updates are cool, but how to update so we don't break the installation or cause errors? 

Just upload the new upload folder and merge/overwrite files? Or do we have a sequence of actions how to do it properly?

**Comment by tacovansambeek** [comment]
all updates are always made in a way that you can simply upload and overwrite the filed. Please do go to the payment module and check for new settings. (even with no new settings, just save the current settings to be sure all new functionalities are active)

**Comment by ibotu** [comment]
cool thanks. 
And how to downgrade?
Sometimes in an upgrade we get unwanted behavior.

**Comment by QualityWorks** [comment]
downgrade would be a manual action, delete all the files and remove database entried. Then upload the old version.

**Comment by ibotu** [comment]
Thanks sounds logical!
