### ISSUE TITLE
Mollie used to receive all payments in €, now it's in the customers currency

### ISSUE THREAD

**Issue by ibotu** [mollie/OpenCart#158]
We want to see all our payments in our Mollie dashboard in Euro.
This used to be like that, but again after update the behavior is changed into the customers currency.

We want to force this to €. How is this possible?
Mollie version 9.0 ; Opencart 2.3.x

**Comment by ibotu** [comment]
updated mollie to 9.0.5

**Comment by QualityWorks** [comment]
as explained on the Opencart forum, this is default behaviour since 9.x. We are discussing to add an option to force the currency. 
And yes, always update ;)
