### ISSUE TITLE
witte pagina

### ISSUE THREAD

**Issue by sterrek** [mollie/OpenCart#16]
Als de klant wil betalen en klikt op bestelling plaatsen. word de klant door gestuurd naar een witte pagina : http://example.com/index.php?route=payment/mollie_ideal/payment

Error setting up transaction with Mollie: A payment already exists for order id 896..
2015-02-21 0:37:49 - PHP Notice:  Use of undefined constant HTTP_ADMIN - assumed 'HTTP_ADMIN' in htdocs/catalog/controller/payment/mollie_ideal.php on line 452

Je ziet niks op de pagina.
ik gebruik opencart 2.0 
nieuwste mollie opencart plugin

**Comment by lvgunst** [comment]
Hallo sterrek. Dit probleem is opgelost in [release 5.2.7](https://github.com/mollie/OpenCart/releases/tag/v5.2.7) van afgelopen donderdag. Heb je deze versie al geprobeerd?

**Comment by sterrek** [comment]
ik gebruikte de nieuwste versie al. probleem bestaat na opnieuw installeren nog.

**Comment by lvgunst** [comment]
Dat is raar. 5.2.6 bevat de fout, in 5.2.7 zou het juist opgelost moeten zijn. Kunt u het bestand catalog/controller/payment/mollie_ideal.php controleren? De methode getAdminDirectory op regel 450 zou er zo uit moeten zien:

```
protected function getAdminDirectory()
{
	// if no default admin url defined in the config, use the default admin directory.
	if (!defined('HTTP_ADMIN'))
	{
		return 'admin/';
	}
	return str_replace(HTTP_SERVER, '', HTTP_ADMIN);
}
```

**Comment by Daanvm** [comment]
Is dit probleem al opgelost? Als je dit probleem nog steeds hebt, kan je het beste contact opnemen via info@mollie.com.

**Comment by sterrek** [comment]
Beste, sorry voor de laate reactie. na mijn back up was alles weer goed.

protected function getAdminDirectory()
{
    // if no default admin url defined in the config, use the default admin directory.
    if (!defined('HTTP_ADMIN'))
    {
        return 'admin/';
    }
    return str_replace(HTTP_SERVER, '', HTTP_ADMIN);
}

Dit stond er idd zo in.

**Comment by Daanvm** [comment]
Goed om te horen dat het weer werkt.
