### ISSUE TITLE
No order in backend after payment

### ISSUE THREAD

**Issue by TiaID** [mollie/OpenCart#162]
I did update mollie from 9.0.1 to Release 9.1.1.

When people did made an order, the order was not in my backend. I could only see it in Mollie. I also only recieved the email from the payment.

I did removed mollie, uploaded it again and did a test, that was going alright. After setting it from test to live the next order I did not see it in my backend.

To be sure Im back at mollie 9.0.1 again.

**Comment by dhuitin** [comment]
Same here in 9.1.1 on OC 2.3.0.2  

Payment is completed but no order in the backend. Happend on several different occasions

**Comment by youri13pixels** [comment]
Same here, I just updated to the latest version 9.1.2. and will check whether the same problem persists.

**Comment by QualityWorks** [comment]
it should be fixed on 9.1.2
