### ISSUE TITLE
Apple pay not showing front end 9.1.1. 

### ISSUE THREAD

**Issue by inekestijnman** [mollie/OpenCart#163]
I am testing version 9.1.1. with OC 2.3.02
On admin side I can install and activate Apple Pay. I enabled for all zones. But it is not showing on the front end as payment option.

(dutch address used)
![Naamloos](https://user-images.githubusercontent.com/46712328/64527744-ff6b5700-d306-11e9-97e4-eb5e022302dc.png)

![Naamloos](https://user-images.githubusercontent.com/46712328/64527618-b0bdbd00-d306-11e9-914d-16f39cb1bb4e.png)

**Comment by youri13pixels** [comment]
they are working on it.. :)
![image_2019_08_26T13_22_13_327Z](https://user-images.githubusercontent.com/17879045/64532061-131bbb00-d311-11e9-9d55-869844749aa2.png)
![image_2019_08_26T13_22_40_602Z](https://user-images.githubusercontent.com/17879045/64532087-1dd65000-d311-11e9-997f-b7f64dc48750.png)

**Comment by inekestijnman** [comment]
tested 9.1.2 on ipad 10 pro with test-apikey. Apple pay showed as payment option.
