### ISSUE TITLE
release 9.1.2 Undefined index: name_mollie_bitcoin

### ISSUE THREAD

**Issue by inekestijnman** [mollie/OpenCart#167]
I am still in testing mode. (opencart 2.3.0.2 Mollie 9.1.2)

When opening the extension page for payments i get:
PHP Notice:  Undefined index: name_mollie_bitcoin in ...admin/language/english/payment/mollie_bitcoin.php on line 4

**Comment by QualityWorks** [comment]
that should not happen if you click to install any of the green buttons behind mollie payments on the payments overview page

**Comment by inekestijnman** [comment]
I clicked one of the edit buttons instead, that fixed it too. thanks.
