### ISSUE TITLE
No order id send to checkout/success page

### ISSUE THREAD

**Issue by myildiz94** [mollie/OpenCart#168]
After update from mollie version 7 to 9.1.2 the order id is being unset from the session data, which results in no order information passed to the success page.

In my case this resulted in the plug-in "Google Analytics Expert" not sending e-commerce data to Google Analytics.

I fixed it by removing the following line: 

unset($this->session->data['order_id']);

from file: catalog/controller/mollie/base.php line 1141

Can this be fixed in the future update?

**Comment by myildiz94** [comment]
Also the code in the base.php file for clearing the cart and unsetting session data is in my opinion unnecessary for oc version 2.3.0.2.

The same code is already present in te file catalog/controller/checkout/success.php from line 6

**Comment by QualityWorks** [comment]
good spot, we will update this in the next update

**Comment by QualityWorks** [comment]
This has been fixed in the latest release(s)
