### ISSUE TITLE
bestand bestaat niet

### ISSUE THREAD

**Issue by zoulou101** [mollie/OpenCart#17]
Achter instal

bij de status

Bestand bestaat niet: "/var/www/vhosts/*/catalog/view/theme/default/template/payment/mollie_payment_error.tpl"
Bestand bestaat niet: "/var/www/vhosts/*/catalog/view/theme/default/template/payment/mollie_payment_error_2.tpl"

**Comment by mollierobbert** [comment]
Thanks for your feedback zoulou101. We've updated our module just now to fix this issue. Please download the latest release here (6.0.1): https://github.com/mollie/OpenCart/releases
