### ISSUE TITLE
Fatal error: 'Error executing API call (404: Not Found): No payment exists

### ISSUE THREAD

**Issue by livewirerules** [mollie/OpenCart#171]
Hi

Upgraded Mollie to the latest version and how when i try to view the order details it gives me the below error

Fatal error: 'Error executing API call (404: Not Found): No payment exists with token tr_xxxxxxxxx.. Documentation: https://docs.mollie.com/guides/handling-errors' 

How can i fix it?

**Comment by QualityWorks** [comment]
Can you please update to version 9.1.5 and try again?
