### ISSUE TITLE
HTTP error 500 when editing any of the mollie settings

### ISSUE THREAD

**Issue by elleng85** [mollie/OpenCart#174]
Whenever I try to edit any of the mollie payment methods (whether they're installed or not), I get an internal server error (500).

I then tried to enable a new method, and now they're all displaying the edit and uninstall icons, even though most of them show the "disabled" status in the overview.

(AFAICT the payment methods do work.)

**Comment by QualityWorks** [comment]
Can you please email us your shop details? what version you're on (opencart version and mollie module version)
also. if you have it, the 500 error details from the logs. 
I have just double-checked on mollie 9.1.5, we are not getting this error.
Let's have a look where it comes from.

**Comment by elleng85** [comment]
I'm using OpenCart Version 2.1.0.2.
The error also appears when I'm trying to view orders. I know this wasn't the case before, so I'm 99% sure this is caused by the mollie update (9.1.5).
Could you let me know how I can find more info about why this error is showing up? The OpenCart logs don't show any incidents regarding this issue.
Thanks!

**Comment by elleng85** [comment]
Meanwhile I've found the error logs in my admin panel (not in the OpenCart admin) that shows me the following (one error caused by trying to edit the settings of the payment method, the other one trying to view an order)

```
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method ModelSettingSetting::getSettingValue() in ...public_html/catalog/controller/payment/mollie/helper.php:136
Stack trace:
#0 /home/-----/domains/shop.-----.be/public_html/admin/controller/payment/mollie/base.php(88): MollieHelper::getApiKey(0)
#1 /home/-----/domains/shop.-----.be/public_html/admin/controller/payment/mollie/base.php(756): ControllerPaymentMollieBase->getAPIClient(0)
#2 /home/-----/domains/shop.-----.be/public_html/vqmod/vqcache/vq2-system_engine_action.php(46): ControllerPaymentMollieBase->index(Array)
#3 /home/-----/domains/shop.-----.be/public_html/system/engine/front.php(34): Action->execute(Object(Registry))
#4 /home/-----/domains/shop.-----.be/public_html/system/engine/front.php(29): Front->execute(Object(Action))
#5 /home/-----/domains/shop.-----.be/public_html/admin/index.php(181): Front->dispatch(Object(Action), Object(Action))
#6 {main}
  thrown in /home/-----/domains...
', referer: https://www.shop.-----.be/admin/index.php?route=extension/payment&token=---

Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method ModelSettingSetting::getSettingValue() in /home/-----/domains/shop.-----.be/public_html/catalog/controller/payment/mollie/helper.php:136
Stack trace:
#0 /home/-----/domains/shop.-----.be/public_html/vqmod/vqcache/vq2-admin_controller_sale_order.php(928): MollieHelper::getApiKey('0')
#1 /home/-----/domains/shop.-----.be/public_html/vqmod/vqcache/vq2-system_engine_action.php(46): ControllerSaleOrder->info(Array)
#2 /home/-----/domains/shop.-----.be/public_html/system/engine/front.php(34): Action->execute(Object(Registry))
#3 /home/-----/domains/shop.-----.be/public_html/system/engine/front.php(29): Front->execute(Object(Action))
#4 /home/-----/domains/shop.-----.be/public_html/admin/index.php(181): Front->dispatch(Object(Action), Object(Action))
#5 {main}
  thrown in /home/-----/domains/shop.-----.be/public_html/catalog/controller/payment/mollie/helper.php on line 136
', referer: https://www.shop.-----.be/admin/index.php?route=sale/order&token=---&filter_order_status=19,2,1
```

Any help would be greatly appreciated!

**Comment by QualityWorks** [comment]
I've found the bug and fixed it (I think)... just doing a test now on all versions of OC and will release 9.1.6 once confirmed.

**Comment by QualityWorks** [comment]
I just released 9.1.6 please update the module by uploading the new helper.php, this file should go into /catalog/controller/payment/mollie/helper.php
[helper.zip](https://github.com/mollie/OpenCart/files/3826207/helper.zip)

**Comment by elleng85** [comment]
Ah, it's fixed. Thanks so much & have a great weekend!

**Comment by Samueljah** [comment]
Hello @QualityWorks, I'm having the same problem every time I click the edit button in admin page it goes to the HTTP error 500, everything else works without a glitch. I'm using the latest OC and Mollie, and there's no notice about this in the error log. Your assistance would be appreciated.

**Comment by QualityWorks** [comment]
can you email us on support.mollie@qualityworks.eu with admin and ftp access? we can have a look for you

**Comment by kionaJ** [comment]
Hi I have the same Issue:

Opencart version: 3.0.2.0
Mollie version I do not know where to find the version.
All is active but a soon as I want to edit a mollie I get a 500 error
