### ISSUE TITLE
Mollie components: Order can not be completed (Journal theme)

### ISSUE THREAD

**Issue by gdegraaf** [mollie/OpenCart#184]
When Mollie components is activated the order can not be completed
![Screenshot 2019-12-10 at 21 02 46](https://user-images.githubusercontent.com/1894150/70703596-bd203000-1cd0-11ea-995f-77b980a8c809.png)
. After clicking 'confirm order' the button says 'loading' and the process doesn't continue.

OC: 3.0.2.0
Journal: 2.16.8

**Comment by QualityWorks** [comment]
This should be fixed in the latest version, can you update and try again?
