### ISSUE TITLE
Error notice on dashboard

### ISSUE THREAD

**Issue by seya78** [mollie/OpenCart#187]
Hello i have this message on the dashboard :

Notice: Undefined index: tag_name in /www/vqmod/vqcache/vq2-admin_controller_common_dashboard.php on line 23

line23 is : 

                if ($info["tag_name"] && $info["tag_name"] != MollieHelper::PLUGIN_VERSION && version_compare(MollieHelper::PLUGIN_VERSION, $info["tag_name"], "<")) {
                    $this->load->language('payment/mollie_ideal');

i'm using opencart 3.0.3.1

is there a way to resolve this issue ?

Best Regard.

**Comment by QualityWorks** [comment]
Thanks for mentioning this. We are working on a new release with a fix for this now.
