### ISSUE TITLE
Multi store api details

### ISSUE THREAD

**Issue by Doublemedia** [mollie/OpenCart#19]
Any plans on making this multi store so you can set api details for the different webshops?

**Comment by lvgunst** [comment]
Currently we have no direct plans for adding support for multi store functionality, but I will add it to our todo list.

**Comment by Doublemedia** [comment]
Oke, well it is multi store, but then you have to set the APIkey in the settings table with his own store_id. Opencart will first check if there are any rows for the used store and else it will fallback on the default store. But it would be nice to have this in the admin.

**Comment by RicardoJ** [comment]
@Doublemedia: The multi-store compatibility has been added in [version 6.2.5](https://github.com/mollie/OpenCart/releases/tag/v6.2.5).
