### ISSUE TITLE
How can I configure a fixed currency to pay

### ISSUE THREAD

**Issue by ibotu** [mollie/OpenCart#191]
version 9.2.3  ; oc 2.3.0.2

Altho we want customers to see their local currency while browsing, we want all payments to be paid with EUR, our shop default currency. 

How can we configure here that the default currency is always used?  

Which is EUR.
currency_id: "3"
currency_code: "EUR"
currency_value: "1.00000000"

I think this piece of code is where it happens:

    protected function convertCurrency($amount) {
        $currency = Util::load()->model("localisation/currency");
        $currencies = $currency->getCurrencies();
        $convertedAmount = $amount * $currencies[$this->session->data['currency']]['value'];

        return $convertedAmount;
    }

In the old version I did:

    protected function convertCurrency($amount) {
        //$currency = $this->session->data['currency'];
        // changed this to "EUR" to enforce conversion of the amount to EUR (when site is going to mollie)
        $currency = "EUR";
        $configCurrency = $this->config->get("config_currency");
        return $this->currency->convert($amount, $configCurrency, $currency);
    }

**Comment by QualityWorks** [comment]
this option has been added in the latest version
