### ISSUE TITLE
after update, mollie plugin shows 2 times in opencart / extensions

### ISSUE THREAD

**Issue by ibotu** [mollie/OpenCart#192]
see attachment, in opencart admin panel, mollie shows up twice

<img width="1263" alt="Screenshot 2020-01-26 at 00 24 05" src="https://user-images.githubusercontent.com/5132081/73128610-45813880-3fd2-11ea-9027-3c672ad1f298.png">
<img width="1267" alt="Screenshot 2020-01-26 at 00 24 10" src="https://user-images.githubusercontent.com/5132081/73128611-474afc00-3fd2-11ea-8b24-ac5621cb7f46.png">

**Comment by QualityWorks** [comment]
if you enter the module, it should be fixed.
