### ISSUE TITLE
currency errors

### ISSUE THREAD

**Issue by ibotu** [mollie/OpenCart#193]
version 9.2.3  ; oc 2.3.0.2

2 currencies are not working. 
Israeli sheikel (ILS)
Icelandic krona (ISK)

Fatal error: Uncaught Mollie\Api\Exceptions\ApiException: Error executing API call (400: Bad Request): The amount contains an invalid value. Field: amount.value. Documentation: https://docs.mollie.com/guides/handling-errors in /xx/xx/xx/catalog/controller/payment/mollie-api-client/src/Exceptions/ApiException.php:78 Stack trace: #0 /xx/xx/xx/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(410): Mollie\Api\Exceptions\ApiException::createFromResponse(Object(_PhpScoper5ce26f1fe2920\GuzzleHttp\Psr7\Response)) #1 /home/xx/xx/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(387): Mollie\Api\MollieApiClient->parseResponseBody(Object(_PhpScoper5ce26f1fe2920\GuzzleHttp\Psr7\Response)) #2 /home/xx/xx/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(348): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) #3 /home/xx/xx/catalog/controller/paymen in /home/xx/xx/catalog/controller/payment/mollie-api-client/src/Exceptions/ApiException.php on line 78

**Comment by QualityWorks** [comment]
this should be fixed in the latest release
