### ISSUE TITLE
Error in checkout page after update

### ISSUE THREAD

**Issue by seya78** [mollie/OpenCart#195]
The module dont show anymore after update : 

Error on extension in admin extension page : 
Notice: Undefined index: tag_name in www/admin/controller/payment/mollie/base.php on line 981
Notice: Undefined index: tag_name in www/admin/controller/payment/mollie/base.php on line 981

https://prnt.sc/quvh7r

Please we need a quick fix.

Best Regard.

**Comment by QualityWorks** [comment]
we are testing an update to fix this. We hope to release it today

**Comment by QualityWorks** [comment]
Took a bit longer but version 9.2.4 has been released and should fix this
