### ISSUE TITLE
Cannot declare class ControllerPaymentMollieBase

### ISSUE THREAD

**Issue by marc-linda** [mollie/OpenCart#196]
Sinds de update van 9.2.2 naar 9.2.3 krijgen we de melding:

Fatal error: Cannot declare class ControllerPaymentMollieBase, because the name is already in use in /home/host/domains/site.nl/public_html/vqmod/vqcache/vq2-catalog_controller_payment_mollie_base.php on line 1429

Ontvangen op url:
https://site.nl/index.php?route=payment/mollie_ideal/callback&order_id=*

Website staat op een online testomgeving.
Foutmelding is ontstaan na de update.

**Comment by marc-linda** [comment]
Was vergeten de versie er bij te vermelden ;-)
Het gaat om oc 3.0.3.2

**Comment by QualityWorks** [comment]
we zijn nu een update aan het doortesten die oa dit zou moeten oplossen.

**Comment by QualityWorks** [comment]
versie 9.2.4 is nu released en zou dit op moeten lossen
