### ISSUE TITLE
Betaal opties kunnen niet worden toegevoegd.

### ISSUE THREAD

**Issue by marc-linda** [mollie/OpenCart#200]
Na de update naar 9.2.4. zijn de "500" status problemen in de checkout verholpen.
Het is alleen niet langer mogelijk om een betaaloptie te activeren.

Na het klikken in de lijst met betaalopties op mollie giftcard, deze aan te vinken en dan te klikken op opslaan resulteert een scherm met de admin login pagina met daarop "Waarschuwing: Ongeldige sessie-token. Log opnieuw in.".

Mollie versie 9.2.4.
Oc 3.0.3.2
Fouten logboek geeft helaas niets aan.

**Comment by QualityWorks** [comment]
dit is in de latere versies opgelost
