### ISSUE TITLE
Mollie v9.2.6 DB update error in 5_updatePrimaryKey.php

### ISSUE THREAD

**Issue by DomoticX** [mollie/OpenCart#203]
Got error when updating Mollie

upload\admin\patch\mollie\5_updatePrimaryKey.php

[Wed Feb 26 17:22:36 2020] [error] PHP Fatal error:  Uncaught Exception: Error: Duplicate entry '' for key 'PRIMARY'<br />Error No: 1062<br />ALTER TABLE `oc_mollie_payments` DROP PRIMARY KEY, ADD PRIMARY KEY (mollie_order_id) in /system/library/db/mysqli.php:40
[Wed Feb 26 17:22:36 2020] [error] Stack trace:
[Wed Feb 26 17:22:36 2020] [error] #0 /system/library/db.php(45): DB\MySQLi->query('ALTER TABLE `oc...')
[Wed Feb 26 17:22:36 2020] [error] #1 /admin/patch/mollie/5_updatePrimaryKey.php(6): DB->query('ALTER TABLE `oc...')
[Wed Feb 26 17:22:36 2020] [error] #2 /system/comercia/patch.php(65): comercia\Patch->{closure}()
[Wed Feb 26 17:22:36 2020] [error] #3 /system/comercia/patch.php(59): comercia\Patch->runPatches(Array, '/var/www/vhosts...')
[Wed Feb 26 17:22:36 2020] [error] #4 /admin/controller/payment/mollie/base.php(250): comercia\Patch->runPatchesFromFolder('mol

**Comment by jojorNL** [comment]
Same problem, It seems to help to disable 5_updateprimaryKey.php in /admin/patch/mollie/

**Comment by QualityWorks** [comment]
Yes, disabling that file should work. It basically means that the primary key is already set correctly.
We will update the file tomorrow to fix this.

**Comment by QualityWorks** [comment]
this should be fixed in the latest release
