### ISSUE TITLE
Payment type shows text_title on order info and invoice

### ISSUE THREAD

**Issue by nebur634** [mollie/OpenCart#207]
Payment type shows text_title on order info and invoice - instead of iDEAL
Opencart version 3.0.3.2 with only Dutch as language both on front-end and admin.

![image](https://user-images.githubusercontent.com/20298603/77250566-248f3980-6c49-11ea-88e1-3bea4dac423b.png)

**Comment by QualityWorks** [comment]
This is an issue with PDF Invoice PRO, it tries to overwrite the language and load it using a file that doesn't exist in our module. We'll work on a patch for this next week.

**Comment by nebur634** [comment]
Excellent, thanks!
