### ISSUE TITLE
Journal 3 checkout

### ISSUE THREAD

**Issue by mr-Kris** [mollie/OpenCart#210]
Opencart 2.3.0.2
Journal 3.0.46
Mollie 9.2.8

Klant plaatst een bestelling, in betaalmethode annuleert deze, probeert vervolgens direct opnieuw af te rekenen, betaling is succesvol echter in de webwinkel krijgt de klant te zien dat de betaling is mislukt. In backoffice staat de bestelling op geannuleerd, klant krijgt geen mail bevestiging, in Mollie dashboard is de betaling succesvol. Ook al probeert de klant meerdere malen opnieuw te betalen, in de webwinkel zal de klant mislukt zien terwijl in Mollie de betalingen wel gewoon op succesvol staan (bestelnummer krijgt geen update)
Met de normale checkout heb ik dit probleem niet, zelf denk ik dat dit komt omdat de normale checkout voor elke betaalpoging dat je doet een nieuw bestelnummer aanmaakt terwijl Joural checkout hetzelfde bestelnummer blijft gebruiken.

Ook heb ik last van dubbele betalingen, maar heb hiervan nog geen directe oorzaak gevonden, maar vermoedelijk hetzelfde probleem (Journal checkout dat hetzelfde bestelnummer gebruikt voor elke betaalpoging).

**Comment by QualityWorks** [comment]
We hebben het zojuist getest in onze Journal3 omgeving, maar kunnen dit probleem niet reproduceren. Wellicht hebben jullie nog andere modules geïnstalleerd die iets met de sessie data doen?

**Comment by mr-Kris** [comment]
Ben nog aan het testen maar het lijkt opgelost te zijn door onderstaande te veranderen.
comercia_util.xml
 <file name="catalog/view/theme/*/template/common/header.tpl">
        <operation error="log">
            <search position="after"><![CDATA[<head>]]></search>
            <add><![CDATA[<?php echo comercia\util::html()->variables();?>]]>
            </add>
        </operation>
    </file>
Aanpassen naar:
<file name="catalog/view/theme/*/template/common/header.tpl">
        <operation error="log">
            <search position="after"><![CDATA[<head typeof="og:website">]]></search>
            <add><![CDATA[<?php echo comercia\util::html()->variables();?>]]>
            </add>
        </operation>
    </file>

**Comment by QualityWorks** [comment]
we nemen dit mee in de komende update (vandaag waarschijnlijk). wel vreemd dat wij dit probleem niet hadden in onze test.
