### ISSUE TITLE
MIssing translations

### ISSUE THREAD

**Issue by osworx** [mollie/OpenCart#213]
Several translations are missed through the whole extension.
Especially bad, if the customer does not understand English, becuase these values are hardcoded!

For example in the base controller:
https://github.com/mollie/OpenCart/blob/cce5b4d9e5521a0e55cc5480f5acacdb44466f3b/admin/controller/payment/mollie/base.php#L895

By a simple adding a 
`Util::load()->language('payment/mollie');`
at the beginning of the functions, these values could be also translated and displayed in users language.
With that, lines like these 
`return '<span style="color:red">API client not found.</span>';`
could be simply changed to something like:
`return '<span style="color:red">' . $this->language->get( 'msg_base_no_api' ) . '</span>';`

The more a few lines below where a more or less "technical" message is used:
`. '<li>Make sure SSL v3 is disabled on your server. Mollie does not support SSL v3.</li>'
. '<li>Make sure your server is up-to-date and the latest security patches have been installed.</li>'`
And so on ..

**Comment by QualityWorks** [comment]
we're updating some of this in the next version
