### ISSUE TITLE
Check if $client is initialized

### ISSUE THREAD

**Issue by osworx** [mollie/OpenCart#214]
https://github.com/mollie/OpenCart/blob/cce5b4d9e5521a0e55cc5480f5acacdb44466f3b/admin/controller/payment/mollie/base.php#L920

Because the extension can be closed without saving an API key (or an invalid like a space), opening the next time results in an error:

> Notice: Undefined variable: client in admin\controller\payment\mollie\base.php on line 922

To avoid that, simply add a 
`isset($client)`
to that.

Or check the fields before the extension can be closed/saved.

**Comment by QualityWorks** [comment]
this will be fixed in the next release
