### ISSUE TITLE
Calling home (Mollie) with every checkout and in the backend

### ISSUE THREAD

**Issue by osworx** [mollie/OpenCart#219]
With every checkout using one of the Mollie payment methods, the Mollie server is called several times only to load everytime again images/icons.
 
This is done in the model and the controller, output in the view.

https://github.com/mollie/OpenCart/blob/cce5b4d9e5521a0e55cc5480f5acacdb44466f3b/catalog/model/payment/mollie/base.php#L185

https://github.com/mollie/OpenCart/blob/cce5b4d9e5521a0e55cc5480f5acacdb44466f3b/catalog/controller/payment/mollie/base.php#L240

https://github.com/mollie/OpenCart/blob/cce5b4d9e5521a0e55cc5480f5acacdb44466f3b/catalog/view/theme/default/template/payment/mollie_checkout_form.tpl#L46

While something like this should be avoided (e.g. bandwith, local development wo. internet, privacy), it would be much more clever to get these images/icons once (maybe at the installation process), and call then the locale stored images.
Same is valid for the "advertising" image (the padlock) and text at the final checkout page.

Same is valid in the backend, instead of storing these images locally once, they are always called from the mollie website with every action.

It must be enough to call Mollie via the API several times, no need to use external images/icons.

**Comment by QualityWorks-Dev** [comment]
Agreed,

We will change this in the next update.

Op zo 10 mei 2020 11:25 schreef OSWorX <notifications@github.com>:
