### ISSUE TITLE
Klant annuleert order betaald 5 min later

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#221]
Hoi,

Had zojuist een raar iets en weet ook niet of het van jullie is of van OC zelf.
Wat gebeurde er: Een klant annuleert in de webshop de order hij blijft op het betaal scherm (waarschijnlijk) krijg van OC een mail dat de klant de order geannuleerd heeft. 5 minuten later krijg ik van mollie een push bericht in de app dat de zelfde order toch betaald is. In de app zie je ook 2 regels eentje betaald en eentje geannuleerd. Krijg echter geen nieuwe mail dat de order nu wel betaald is.

Martijn

**Comment by QualityWorks** [comment]
Kan je ons wellicht een kopie van de log sturen zodat we even mee kunnen kijken? support.mollie@qualityworks.eu

**Comment by telemoes** [comment]
Taco had er zojuist weer eentje en deze order is dus ook naar de leverancier gegaan.

**Comment by QualityWorks** [comment]
als het goed is, is dit in 9.3.1 opgelost

**Comment by telemoes** [comment]
Ik heb de plug-in geupdated we gaan het bekijken of het weer gebeurd. Waar kwam het nou precies door?

**Comment by QualityWorks** [comment]
bij de callback keken we naar de betaalstatus, zowel "paid" als "open" werden op als "paid" gezien,  een bug dus. Maar de collega die de bug aan het uitzoeken was, dacht dat dat correct was en had dat dus niet gezien als een fout.

**Comment by telemoes** [comment]
Gisterenavond en zelfde geval gehad alleen nu kreeg ik een mail met de melding "We wachten nog op de betaling. U krijgt een email zodra de status van de betaling bij ons bekend is.". Klant betaalde met iDEAL deze liet hij verlopen en betaalde later als nog.
De order bleef in OpenCart op status afwachten staan. Is het mogelijk dat als de klant als nog betaald heeft om de order wel de juiste status te geven of is dit niet mogelijk?

De order is in mijn geval nu niet verstuurd naar de leverancier wat dus beter is.

**Comment by QualityWorks** [comment]
die zou al geüpdate moeten worden. Kan je de mollie log naar ons toe mailen?

**Comment by telemoes** [comment]
Verstuurd via mail!

**Comment by telemoes** [comment]
Dit is nog steeds niet opgelost ik heb screenshots gemaakt van een klant waarvan eerst de betaling is verlopen en later als nog betaald blijft in OC de status op afwachtend met als gevolg dat de order dus niet verstuurd word naar de leverancier.
