### ISSUE TITLE
ocmod in plaats van VQMod

### ISSUE THREAD

**Issue by kllr** [mollie/OpenCart#222]
Hi,

Kunnen jullie de tool zonder VQMod beschikbaar maken? Dat wordt zelden meer gebruikt ivm het nieuwere ocmod. Daarnaast werkt VQMod niet met de modernere themes/ site templates.

Noodgedwongen moet ik nu Stripe gebruiken en ik wil weer Mollie kunnen gebruiken.

Alvast bedankt. 
mvg

**Comment by QualityWorks** [comment]
wij zijn nog geen theme tegen gekomen die niet met vQmod werkt, zou ook onlogisch zijn, het is immers niet een theme gerelateerde functie.. Tevens zijn er in de latere versies van OCmod restricties geïntroduceerd die het lastig maken om alles uit te voeren wat wij willen doen.
vQmod wordt ook bij 3.x nog veelvuldig gebruikt, dit werkt prima in combinatie met ocmod. Helaas is het momenteel niet mogelijk om een OCmod versie van de Mollie module te maken.
Theoretisch is de XML aan te passen en deze als ocmod te installeren, echter kunnen we niet de gehele module als ocmod aanbieden, de installer zal dat niet accepteren.

**Comment by kllr** [comment]
Bedankt voor het antwoord.

http://fastortheme.com/ is de template die ik gebruik en die werkt niet met vQmod. Heb ook de maker gevraagd, maar gaat hem niet worden helaas.

Jammer dat het niet zomaar gaat. In dat geval ga ik zelf converteren of laten converteren. De XML had ik al omgezet maar de tpl's en de rest nog niet.

**Comment by QualityWorks** [comment]
ik snap het probleem niet, de theme hoeft niet echt iets te doen toch? je kan gewoon vqmod installeren? zou moeten werken.
Als je het om wil zetten naar ocmod hoef je alleen de xml's om te zetten, de rest niet, dat wordt gewoon opgepakt door de module. alleen moet je dan de bestanden wel handmatig uploaden

**Comment by kllr** [comment]
Dank je, zou top zijn. Ik zal de theme even naar je mailen. 
Mocht het makkelijker zijn, dan kan ik ook een user aanmaken voor je op de vps en in opencart.
