### ISSUE TITLE
Mollie 9.3.1 is breaking plugins due to payment images

### ISSUE THREAD

**Issue by DomoticX** [mollie/OpenCart#224]
We use TCPDF to create invoices, after updating mollie to v9.3.1....TCPDF is not able to get the filesize of the payment images and the PDF plugin breaks, whereas the rest of the shop images work fine....strange... i tried to fix it but no luck atm...

Ps. i also noticed some RELATIVE PATHS! in multiple base.php (and other PHP files) etc, don't know if that is the issue, but it should be adressed with full/absolute paths from the config, e.g. like:

`$payment_method['icon']    = "../image/mollie/" . $module_name . "2x.png";`

to

`$payment_method['icon']    = DIR_IMAGE . "mollie/" . $module_name . "2x.png";`

Using mollie 9.3.1 and OC 3.0.3.2

**Comment by DomoticX** [comment]
![tcpdf error](https://user-images.githubusercontent.com/8792334/84178780-47c9c800-aa85-11ea-8d3a-0f9578b79ec7.png)

**Comment by DomoticX** [comment]
For what it s worth...i have checked the database:

table: oc_order
column: payment_code

when i REVERT the error (string is):
`<img src="https://webshop.domoticx.nl/image/mollie/ideal.png" height="20" style="margin:0 5px -5px 0" />iDEAL`

back to:

`<img src="https://www.mollie.com/external/icons/payment-methods/ideal.png" height="20" style="margin:0 5px -5px 0" />iDEAL`

it works then....no clue what is wrong with the code though....or TCPDF...i am really stunned atm what the cause could be...

**Comment by beireken** [comment]
Is this still happening when we disable the images in mollie settings? ( as a temporary fix )

**Comment by DomoticX** [comment]
> Is this still happening when we disable the images in mollie settings? ( as a temporary fix )

We have disabled the images as **temporally fix**, that seems to work for now....

**Comment by beireken** [comment]
Ok, thank you @DomoticX

**Comment by DomoticX** [comment]
After some testing it seems the error was a TCPDF temp cache folder setting (K_PATH_CACHE), now placed outside the webspace again (as default)

Not working:
define ('K_PATH_CACHE', '/webspace/httpdocs/.../.../.../tcpdf/tmp/');

Working:
define ('K_PATH_CACHE', '/tmp/');

Hope it might help someone else facing this problem ;-)
