### ISSUE TITLE
Betaalmogelijkheid beschrijving

### ISSUE THREAD

**Issue by beireken** [mollie/OpenCart#225]
Is het enigzins mogelijk om de beschrijving van de betaalmogelijkheden te wijzigen?
Het zou leuk zijn als ik de extra kosten voor sommige mogelijkheden kan vermelden bij het selecteren van een optie.

Bvb Paypal +3.4%

Zo weten de klanten op voorhand al welke kosten er zijn bij een betaalmogelijkheid en hoeven ze niet telkens door te gaan tot de samenvatting.

**Comment by DomoticX** [comment]
@beireken 

Ter info: Officieel mag je extra kosten voor paypal en creditcard niet in rekening brengen, het is geven en nemen bij bepaalde betalingen, leuk leesvoerlijntje: https://www.webwinkelforum.nl/viewtopic.php?t=15681

**Comment by QualityWorks** [comment]
en omdat het officieel niet mag, ondersteund de module het ook niet. we hebben het overwogen en toen besloten het niet te doen

**Comment by beireken** [comment]
Ok, dit wist ik nog niet! Even verder opgezocht en blijkbaar is het in België ook verboden.
Bedankt voor de feedback!
