### ISSUE TITLE
Order wordt overschreven

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#227]
Hoi,

Bij een nieuwe site van mij was ik de plugin (Laatste versie) aan het testen.
Ik had een order gemaakt en deze in het mollie betaalscherm op open gezet. Ik kreeg netjes een e-mail dat ik de order nog moest betalen. Ik bestel een ander product in de webshop en ga opnieuw naar afrekenen en betaal nu wel.
Beide orders hadden ID 4 gekregen met als gevolg dat de order is overschreven met het nieuwe product. Je zou verwachten dat je dus een nieuwe order ID zou krijgen maar dat was niet het geval.

FYI de site staat in test mode dus ook de mollie api key is van test misschien dat dit nog wat uitmaakt.

**Comment by QualityWorks** [comment]
Welke checkout gebruik je? Mollie maakt de bestellingen niet aan, we
verwerken alleen de betalingen.
Wellicht is het handiger om ons te mailen met zo'n specifieke vraag IPV via
GitHub te gaan.


Op ma 6 jul. 2020 22:01 schreef Telemoes <notifications@github.com>:
