### ISSUE TITLE
Update Journal 3 theme - checkout error

### ISSUE THREAD

**Issue by dejokke86** [mollie/OpenCart#228]
Zonet de laatste theme update uitgevoerd (Journal 3.1.1) maar dit geeft nu een fatal error bij checkout.

`/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 39`

**Comment by youri13pixels** [comment]
Hetzelfde probleem hier. Lijkt erop dat journal een aantal wijzigen heeft gemaakt op de checkout. Hierdoor functioneert het niet meer.

**Comment by telemoes** [comment]
Dit zijn de wijzigingen in de checkout:
Fixed One Page Checkout loading button after iframe payment is shown
Fixed One Page Checkout issue when multiple checkout pages are opened

Dit is dus eigenlijk ook de reden dat ik nooit gelijk update ik moest 3.1.0 nog doen van vorige week hier zitten ook diverse wijzigingen in in de checkout.
Na deel voor mollie is dat ze vaak achter de feiten aan lopen hopelijk kunnen ze het snel oplossen

**Comment by QualityWorks** [comment]
We zullen er zsm naar kijken...

Dit is waarom persoonlijk een hekel heb aan Journal (niet alleen vanwege
dit)

Op vr 10 jul. 2020 21:56 schreef Telemoes <notifications@github.com>:

**Comment by telemoes** [comment]
ik snap het ken het nog wel van mijn tijd in de ICT plugins die ineens geupdate worden en dat dan websites niet meer werken. bah!

**Comment by telemoes** [comment]
Als je in het admin van OC naar extensies/payments ga en klik op mollie krijg ik ook een http error 500 ik zal je de log mailen want het heeft volgens mij niet met de checkout specifiek te maken.

**Comment by PetjeNL** [comment]
Ik ervaar precies de zelfde dan @telemoes en als @dejokke86 . Er zijn issues bij de checkout en als je naar extensies/payments gaat krijg je een http 500 error.

**Comment by telemoes** [comment]
@QualityWorks wat is de status inmiddels heeft Journal 2 nieuwe updates uitgebracht.

**Comment by QualityWorks-Dev** [comment]
We zijn nu met de release bezig. Er zat een conflict in de composer van de
Mollie API ivm de nieuwe composer van J3. De update komt er zo aan.

Op vr 31 jul. 2020 14:59 schreef Telemoes <notifications@github.com>:

**Comment by telemoes** [comment]
Goed bezig!

**Comment by youri13pixels** [comment]
Hebben jullie al misschien wat nieuws? Ik zou dolgraag willen update namelijk.

**Comment by QualityWorks** [comment]
de update is zojuist online gezet
