### ISSUE TITLE
Fatal error: Call to undefined function boolval()

### ISSUE THREAD

**Issue by filipburman** [mollie/OpenCart#23]
Hello,
Just installed the new version on my website. But I get Fatal error on call back.
index.php?route=payment/mollie_creditcard/callback

Fatal error: Call to undefined function boolval() in /storage/content/29/153629/****.com/public_html/catalog/controller/payment/mollie/base.php on line 438

When I cancel and order at the payment section. Both for creditcard and iDeal.

**Comment by mollierobbert** [comment]
Thanks for the heads up, Filip. We've patched the issue in our latest release: https://github.com/mollie/OpenCart/releases/tag/v6.1.2

Do let us know if you find anything else.
