### ISSUE TITLE
Permission denied errors while updating the plugin from within the admin panel

### ISSUE THREAD

**Issue by enovision** [mollie/OpenCart#230]
It would be very nice to add some extra documentation in the readme regarding the upgrade process and the permissions required. When I press this button to upgrade to version 9.40 of the extension I get loads of permission errors on the "cpy" function. 

Have you tested this in a docker container on a local desktop/laptop? For sure it would be helpful to have a warning telling that an upgrade is not possible while permissions are insufficient.

One sample line of at least 50 of the same error:
```
Warning: copy(/home/dbimg/web/beheer.db-img.local/public_html/catalog/../vqmod//xml/util.xml): failed to open stream: Permission denied in /home/dbimg/web/beheer.db-img.local/public_html/admin/controller/payment/mollie/base.php on line 1068
```

**Comment by QualityWorks** [comment]
we have tested the update function extensively and also use it for other modules. I would assume there's an owner-issue for the files on the server.

**Comment by enovision** [comment]
> we have tested the update function extensively and also use it for other modules. I would assume there's an owner-issue for the files on the server.

It is a permission error, on a standard Opencart (version 2) installation the admin/controller content for example has a 644 permission on the files and a 755 on the folders and only after modifying this it is accepting the copy file function.

I am running this on an local Apache testserver (a real server). 

But I have it upgraded now after I changed the permissions less strict

Thanks for the fast reply by the way.

**Comment by QualityWorks** [comment]
Most default settings for files is 664, and this should work fine for the update function.
