### ISSUE TITLE
Multiple "Payment received" status

### ISSUE THREAD

**Issue by beireken** [mollie/OpenCart#231]
Not sure if this is an opencart-mollie issue.. but with every order processed through mollie i get multiple payment history items.
This results in multiple order confirmation email's being sent also. The mails are autoprinted so i sometimes have 3x the same order printed :)

This happens with most mollie payment methods (kbc, bancontact, ...) we use.
Screenshots for illustration added.
![Untitled](https://user-images.githubusercontent.com/5359577/92389333-2c6c6880-f119-11ea-99cd-ea3902f799ea.png)

**Comment by paxmar** [comment]
We have the same problem. But it doesnt occur on every order.

**Comment by naarsine** [comment]
Same here, never 3x but sometimes 2x. The customer then receives 2 email confirmations which is a bit annoying. 
We've checked the amount, and on 100 orders by average we have this issue with 4-5 orders.

**Comment by QualityWorks** [comment]
This is "interesting" we've had this issue in the past, but thought we'd fixed it. We'll have another look at it.

**Comment by beireken** [comment]
To the other users experiencing this. Is it also affecting your stock count?
I am noticing that our stock is incorrect and i think it is related to the double created orders with mollie.

Any news on this issue?

**Comment by QualityWorks** [comment]
2 orders being created is not what we are looking at, that may also be because of a different checkout? Some create orders at funky moments. The creation of the order is actually not something that the Mollie module does, it only does the payment, the creation of the order is done by the checkout.
We are looking at the intermittent issue of double confirmation emails, however, we haven't found a cause yet.

**Comment by beireken** [comment]
I'm not sure at this point wat is causing it. There are no real duplicate orders because there is only one order number. 
But in opencart recent activity i see 2 messages for a new order and also receive 2 emails.
And i do think this is only when mollie checkout is used but it is really hard to debug i think.

Isn't there a detailed log anywhere in opencart what happens when an order is created?

**Comment by beireken** [comment]
I have since switched our payments over to pay.nl and we have had no duplicate orders since.

So it was definitely Mollie that was causing this. However I would really like to stay with Mollie.
Any news on V10 to test? I sent an email a while ago to receive it ( as you said in another issue thread ) but got no reply.

**Comment by QualityWorks** [comment]
The V10 has been released!

**Comment by beireken** [comment]
This problem returned when i switched back to Mollie v10, sonnot solved unfortunately.

**Comment by QualityWorks** [comment]
Sorry for the long delay. Is this still an issue? can you please email us on support.mollie@qualityworks.eu?

**Comment by rajivsjmsoftech** [comment]
Every order processed through mollie i get multiple payment history items.
This results in multiple order confirmation email's being sent also. The mails are autoprinted so I sometimes have 3x the same order

**Comment by wrick0** [comment]
This is still a problem in 2023, still receiving double status updates for some orders
