### ISSUE TITLE
Problem with 

### ISSUE THREAD

**Issue by mickey30m** [mollie/OpenCart#232]
i get this error in opencart when i use the latest plugin. 9.4.0 

on the frontend and backend i get this when i rename util.xml to util.xml_ the frontend and backend works but when i open a order i get the error that util.xl is missing. 

Fatal error: Uncaught TypeError: Argument 1 passed to Twig\Environment::addFunction() must be an instance of Twig\TwigFunction, string given, called in /var/www/vhosts/mydomain.nl/domains/mydomain.nl/public_html/system/util/twig.php on line 15 and defined in /var/www/vhosts/mydomain.nl/domains/mydomain.nl/storage/vendor/twig/twig/src/Environment.php:852 Stack trace: #0 /var/www/vhosts/mydomain.nl/domains/mydomain.nl/public_html/system/util/twig.php(15): Twig\Environment->addFunction('html_variables', Object(Twig\TwigFunction)) #1 /var/www/vhosts/mydomain.nl/domains/mydomain.nl/public_html/vqmod/vqcache/vq2-_var_www_vhosts_mydomain.nl_domains_mydomain.nl_storage_modification_system_library_template_twig.php(40): util\Twig->prepare(Object(Twig\Environment)) #2 /var/www/vhosts/mydomain.nl/domains/mydomain.nl/storage/modification/system/library/template.php(59): Template\Twig->render('common/header', '0') #3 /var/www/vhosts/mydomain.nl/domains/mydomain.nl/p in /var/www/vhosts/mydomain.nl/domains/mydomain.nl/storage/vendor/twig/twig/src/Environment.php on line 852

**Comment by QualityWorks** [comment]
You can't remove the util.xml. all parts of the module are needed for
everything to function correctly.

Op za 10 okt. 2020 13:51 schreef mickey30m <notifications@github.com>:

**Comment by mickey30m** [comment]
yes i know but when i dont do it the whole site is down with this error

**Comment by mickey30m** [comment]
i already updated vqmod, and the new mollie extension. i delete my modifications folder inside storage and the cache from vqmod rebuild the modification folder. and vqmod and still same error. 

is there a problem in the extension?

**Comment by QualityWorks** [comment]
We have not seen any issues with the module. Can you please email us on support.mollie@qualityworks.eu ?

**Comment by mickey30m** [comment]
Zie log voor veel fouten die voorkomen 

 

Van: Taco <notifications@github.com> 
Verzonden: dinsdag 20 oktober 2020 11:25
Aan: mollie/OpenCart <OpenCart@noreply.github.com>
CC: mickey30m <michael@beeldsensatie.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [mollie/OpenCart] Problem with (#232)

 

Closed #232 <https://github.com/mollie/OpenCart/issues/232> .
