### ISSUE TITLE
Betaal opties dubbel en krijg mollie niet actief

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#233]
Ik heb de laatste versie van de plugin gedownload voor opencart met thema Journal.
Na installatie zie ik alle Mollie betaal opties dubbel en ik krijg de status niet naar actief met de test API key alle betaal opties blijven op inactief staan.

**Comment by mickey30m** [comment]
heb je de nieuwste versie van vqmod gedownload? 
welke versie opencart? ik heb 3.0.3.6 en aardig wat problemen met modificaties en vqmod. 

ik heb ook journal theme schijnbaar gaat er toch iets niet helemaal goed met journal - mollie - opencart.

**Comment by QualityWorks** [comment]
Kunnen jullie even een email sturen naar support.mollie@qualityworks.eu? dan kunnen we even meekijken.
