### ISSUE TITLE
Mollie - Opencart 3 - OCMOD

### ISSUE THREAD

**Issue by svansteenkiste** [mollie/OpenCart#234]
Mollie werkt momenteel helaas alleen op VQMod, 

Momenteel Webshop OpenCart 3 met OCMod, na installatie Mollie, loopt de webshop vol met errors

**Comment by QualityWorks** [comment]
Hi Stijn, kan je ons mailen op support.mollie@qualityworks.eu ? dan kan ik even meekijken
