### ISSUE TITLE
SEARCH NOT FOUND (SKIPPED): $ignore = array(

### ISSUE THREAD

**Issue by beireken** [mollie/OpenCart#235]
In vqmod log i get a lot of the following errors:

`******************************2_Tue.log*******************************
---------- Date: 2020-11-10 00:38:30 ~ IP : 5.130.72.125 ----------
REQUEST URI : /admin/index.php?route=common/login
MOD DETAILS:
   modFile   : /var/www/html/opencart/vqmod/xml/mollie.xml
   id        : Quality Works - Mollie
   version   : 1.3.8
   vqmver    : 2.3.0
   author    : Quality Works

File Name    : admin/controller/common/login.php(0)
VQModObject::applyMod - SEARCH NOT FOUND (SKIPPED): $ignore = array(
----------------------------------------------------------------------`

Is this something to be ignored or something to look into?

Best regards,
Bart

**Comment by QualityWorks** [comment]
Because the module supports all versions between OC 1.5.6.4 -- 3.0.3.6, there are a lot of searches that are "NOT FOUND" in each version. This is nothing to be worried about.

**Comment by beireken** [comment]
Great, thx for the quick reply!
