### ISSUE TITLE
UPdate loopt vast

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#239]
Ik deed de update naar de nieuwe versie kreeg een foutmelding

[Wed Jan 13 14:08:38.516584 2021] [fcgid:warn] [pid 2843285:tid 140677350188800] [client 82.174.80.253:60861] mod_fcgid: stderr: #4 /public_html/catalog/model/payment/mollie/base.php(130): ModelPaym in /public_html/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 39, referer 

HTTP ERROR 500
Mensen kunnen dus niet meer afrekenen!!!!!

**Comment by QualityWorks** [comment]
ik heb de release terug getrokken, we zien nog een andere bug, we zullen beiden oplossen en een nieuwe release doen.

**Comment by telemoes** [comment]
Thx ik zet inmiddels de backup terug
