### ISSUE TITLE
Fatal Error using V10

### ISSUE THREAD

**Issue by TriumphDesign** [mollie/OpenCart#240]
Hi there,

I'm using the latest (v10) version of the Mollie module.

I installed everything correctly (I think) but when going to the checkout I get the following error:

`Fatal error: Uncaught Exception: Error: Could not load model extension/payment/mollie_banktransfer! in /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/loader.php:89 Stack trace: #0 /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/checkout/payment_method.php(51): Loader->model('extension/payme...') #1 /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/action.php(79): ControllerCheckoutPaymentMethod->index() #2 /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry)) #3 /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index() #4 /home/customer/www/docusv.sg-host.com/public_html/system/engine/router.php(67): Action->execute(Object(Registry)) #5 /home/customer/www/docusv.sg-host.com/public_html/system/engine/router.php(56): Router->execute(Object(Action)) #6 /home/customer/www/docusv.sg-host.com/public_html/system/framework.php in /home/customer/www/docusv.sg-host.com/storage/modification/system/engine/loader.php on line 89`

- I am using the OCMOD version of mollie.
- I am using OpenCart v3.0.3.6
- Tested with my custom template and with the default template. Same error occurs.
- My /Storage folder is in the root, not in public_html

I hope you can help me out!
Thanks a lot in advance.

**Comment by QualityWorks** [comment]
Have you gone into the settings in admin? That should trigger a cleanup function to solve this.
It's trying to load the "old style" payment methods.

**Comment by TriumphDesign** [comment]
The settings of the module itself? Yes have a look:

![image](https://user-images.githubusercontent.com/9880958/104594999-404d4b80-5672-11eb-8a33-bb59a474e4bc.png)

**Comment by TriumphDesign** [comment]
Also note, this is on a fresh installation, no old versions of mollie were used.

**Comment by QualityWorks** [comment]
vreemd. We hebben ook een andere bug gevonden in de v10 module, daarom hebben we de release terug getrokken. we gaan deze oplossen en begin volgende week een nieuwe release doen. We zullen dit ook nakijken.

**Comment by TriumphDesign** [comment]
Dank!
