### ISSUE TITLE
Javascript error in chrome

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#245]
Ik krijg in chrome een javascript error. Betalen werkt wel gewoon maar staat niet echt netjes.

Uncaught ReferenceError: $ is not defined at mollie.js:1

JAVASCRIPT FILE.
$(document).ready(function() {
  if (!window.ApplePaySession || !ApplePaySession.canMakePayments()) {
    // Apple Pay is not available
    if(document.cookie.indexOf('applePay=') == -1) {
    	document.cookie="applePay=0";
    }
  }
});

**Comment by QualityWorks** [comment]
this should all be fixed in 10.1.0, just upload the files from the zip, and optionally, remove the files from storage/modification if you are experiencing errors. (and after you login again, refresh modifications)
