### ISSUE TITLE
Duplicate Mollie Payment Methods appearing in list.

### ISSUE THREAD

**Issue by lifis** [mollie/OpenCart#247]
10.0.1 the Mollie payment method appears twice.
OC v2.3.0.2

Once above NoChex and Once under Worldpay

I know duplicates have been addressed for each payment method within Mollie but there is still 2 Mollie payment methods in the list for me.

![Screenshot 2021-01-25 at 16 30 05](https://user-images.githubusercontent.com/19150256/105734495-98196b80-5f2a-11eb-8dad-b1077090940b.png)

**Comment by QualityWorks** [comment]
Yes we are aware, there is no technical issue while using mollie here. This was supposed to be fixed in 10.0.1 but the fix was actually not correct, we have prepared the correct fix for 10.0.2 that will be released soon.
