### ISSUE TITLE
Foutmelding na upgrade

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#249]
Goedemorgen,

Zojuist de upgrade gedaan naar de nieuwe versie en nu is Mollie uitgeschakeld in de backend en als ik hem wil starten krijg ik een foutmelding

In het admin krijg ik een http error 500
referer: https://www.desnoeptent.nl/admin/index.php?route=extension/extension&token=pBV2vdVyM8JWYoNqt8MeWuZlBhlBHLci
[Fri Jan 29 08:58:48.769995 2021] [fcgid:warn] [pid 3927989:tid 140677341796096] [client 82.174.80.253:50608] mod_fcgid: stderr: #4 /admin/controller/payment/mollie.php(1141 in /catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 39, referer: https://www.desnoeptent.nl/admin/index.php?route=extension/extension&token=pBV2vdVyM8JWYoNqt8MeWuZlBhlBHLci

Foutmelding afrekenen frontend:
Fatal error: Uncaught Exception: Error: Could not load model extension/payment/mollie_applepay! in /vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php:67 Stack trace:
#0 /catalog/model/journal3/checkout.php(594): Loader->model('extension/payme...') 
#1 /catalog/model/journal3/checkout.php(257): ModelJournal3Checkout->payment_methods(7.8044)
#2 /catalog/model/journal3/checkout.php(81): ModelJournal3Checkout->sync() 
#3 /vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php(186): ModelJournal3Checkout->init() 
#4 /system/engine/proxy.php(25): Loader->{closure}(Array, Array) 
#5 /vqmod/vqcache/vq2-catalog_controller_journal3_checkout.php(96): Proxy->__call('init' in /vqmod/vqcache/vq2-system_storage_modification_system_engine_loader.php on line 67

Nu kan er niet worden afgerekend worden in de webshop

**Comment by youri13pixels** [comment]
Same here. 🤔

**Comment by QualityWorks** [comment]
this should all be fixed in 10.1.0, just upload the files from the zip, and optionally, remove the files from storage/modification if you are experiencing errors. (and after you login again, refresh modifications)
