### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by nebur634** [mollie/OpenCart#250]
After upgrading to newest version getting the following errors when opening the extension configuration page. Also the payment method is not available in the checkout process.. Downgrading is not possible, creating even more isssues. Please help.

otice: Undefined index: mollie_api_key in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1147Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1090Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1093Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1103Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1093Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1105Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1093Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1105Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1093Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1105Notice: Undefined index: store_id in /home/<username>/htdocs/admin/controller/payment/mollie.php on line 1093Notice:

**Comment by nebur634** [comment]
Opencart version 2.3.0.2
Mollie Opencart 10.0.1

**Comment by QualityWorks** [comment]
we will release a new version later today that should fix all known problems.

**Comment by nebur634** [comment]
any ETA? Our webshop is now down due to this (second time you pushed out a crappy update)

**Comment by QualityWorks** [comment]
We have it ready

**Comment by QualityWorks** [comment]
this should all be fixed in 10.1.0, just upload the files from the zip, and optionally, remove the files from storage/modification if you are experiencing errors. (and after you login again, refresh modifications)
