### ISSUE TITLE
Mollie Payment module 'missing' after deploying 10.1.0.0 bugfix...

### ISSUE THREAD

**Issue by nebur634** [mollie/OpenCart#252]
Almost weekend guys? After applying the bugfix, now the mollie module is no longer visible as a payment module...

**Comment by QualityWorks** [comment]
you mean no longer visible? can you email us? we'll have a look. it should be working fine, we tested all possible update methods.

**Comment by nebur634** [comment]
Hi,

it's no longer listed as module under payments methods... Checked the permissions & ownership on both the filessystem as groups in opencart twice.. Nothing wrong with it.
(Also the clear cache buttons misteriously disappeared)

Regards,

Ruben

________________________________
Van: Taco <notifications@github.com>
Verzonden: vrijdag 29 januari 2021 17:16
Aan: mollie/OpenCart <OpenCart@noreply.github.com>
CC: Ruben van Gogh <rubenv@ngogh.net>; Author <author@noreply.github.com>
Onderwerp: Re: [mollie/OpenCart] Mollie Payment module 'missing' after deploying 10.1.0.0 bugfix... (#252)


you mean no longer visible? can you email us? we'll have a look. it should be working fine, we tested all possible update methods.

**Comment by QualityWorks** [comment]
we don't do anything with the clear cache button or the modification page in general. Please email us on support.mollie@qualityworks.eu and we'll help you

**Comment by QualityWorks** [comment]
this is fixed. as a reference, I just deeplinked to extension/payment/mollie_ideal and did the setup. The update itself was fine. everything worked after
