### ISSUE TITLE
Opencart checkout crash

### ISSUE THREAD

**Issue by Sgt-Peppet** [mollie/OpenCart#254]
If mollie credit card is enabled, the checkout page crashes (is not loading at all) if the total value in the basked exceeds a certain amount (about 2500$). I assume that this is related to a certain credit restriction of mollie.
We have customers who like to buy some more expensive machines or equipment online but we cannot offer credit card payment anymore due to this issue.

**Comment by QualityWorks** [comment]
We have not seen this before at all. Can you please email us at support.mollie@qualityworks.eu with your store details so we can have a look for you?
