### ISSUE TITLE
Fatal error after canceling payment

### ISSUE THREAD

**Issue by TriumphDesign** [mollie/OpenCart#255]
I was testing the LIVE API key and canceled the payment, got this error when it went to 
/index.php?route=payment/mollie_ideal/callback&order_id=2784:

Errors occur when canceling iDeal & Sofort payment

`Fatal error: Uncaught Mollie\Api\Exceptions\ApiException: Error executing API call (404: Not Found): Order ord_q6xs0a exists, but the wrong mode is used. Try switching live / test API keys.. Documentation: https://docs.mollie.com/guides/handling-errors in /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/payment/mollie-api-client/src/Exceptions/ApiException.php:78 Stack trace: #0 /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(424): Mollie\Api\Exceptions\ApiException::createFromResponse(Object(_PhpScoper5f491826ce6ce\GuzzleHttp\Psr7\Response)) #1 /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(401): Mollie\Api\MollieApiClient->parseResponseBody(Object(_PhpScoper5f491826ce6ce\GuzzleHttp\Psr7\Response)) #2 /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(362): Mollie\Api\MollieApiClient->performHt in /home/customer/www/docusv.sg-host.com/public_html/catalog/controller/payment/mollie-api-client/src/Exceptions/ApiException.php on line 78`

**Comment by TriumphDesign** [comment]
I generated new API codes and I don't get this error with the test API. Everything works fine then.

With the LIVE API I get the error, a client just mailed us that they got the error after having paid.

**Comment by ramondunker** [comment]
I'm getting a similair result. When payment is made it gets the status 'Canceled'. 

Anyone else having this issue?

**Comment by youri13pixels** [comment]
Do you have these setting? Maybe this helps.

![2021-02-09_10h37_22](https://user-images.githubusercontent.com/17879045/107344782-23663580-6ac3-11eb-9758-f38956743d32.jpg)

**Comment by ramondunker** [comment]
![image](https://user-images.githubusercontent.com/6952890/107345015-6c1dee80-6ac3-11eb-9ef6-2259a33bc897.png)

These are my settings!

**Comment by youri13pixels** [comment]
Perhaps you could adjust them and try if the problem persists?

**Comment by ramondunker** [comment]
I found the problem. The orders that got cancelled were paid partly with a coupon code. OpenCart wrongly set these orders to fraudulent and cancelled them. Had nothing to do with Mollie :)

**Comment by youri13pixels** [comment]
Great work! Thanks for letting me know!!!

**Comment by QualityWorks** [comment]
@TriumphDesign  could you check if this is also the same issue for you with the coupons? if not, we will continue to support to find a fix

**Comment by QualityWorks** [comment]
Thanks Youri!

**Comment by QualityWorks** [comment]
We have tried many ways to try to recreate this issue, we cannot. It is possible for you to share your error and mollie logs with us on support.mollie@qualityworks.eu ?

**Comment by TriumphDesign** [comment]
No I am not using any Coupons

**Comment by dennisb1** [comment]
> I found the problem. The orders that got cancelled were paid partly with a coupon code. OpenCart wrongly set these orders to fraudulent and cancelled them. Had nothing to do with Mollie :)

How did you solve this? We have the same issue.
