### ISSUE TITLE
Checkout Crash - GuzzleHttp\choose_handler()

### ISSUE THREAD

**Issue by umagenta683** [mollie/OpenCart#257]
Hello,

I updated to the latest version. Uploaded all files to the website root folder and refreshed modifications. 
However, when visiting the checkout page I get the below stated error. 

Thanks for the great work but it seems that with every update I have to check if everything is still working and most of the time something crashes. Makes me afraid to update the extension.

Please give help **asap** since we can not accept payments at the moment.

OC v. 2.3.0.2.
Mollie v.10.1.1

Fatal error: Uncaught Error: Call to undefined function _PhpScoper5f491826ce6ce\GuzzleHttp\choose_handler() in /home/eleganta/public_html/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/HandlerStack.php:39 Stack trace: #0 /home/eleganta/public_html/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/Client.php(64): _PhpScoper5f491826ce6ce\GuzzleHttp\HandlerStack::create() #1 /home/eleganta/public_html/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php(237): _PhpScoper5f491826ce6ce\GuzzleHttp\Client->__construct(Array) #2 /home/eleganta/public_html/catalog/controller/payment/mollie-api-client/helper.php(77): Mollie\Api\MollieApiClient->__construct() #3 /home/eleganta/public_html/catalog/model/payment/mollie/base.php(58): MollieHelper->getAPIClient(Object(Config)) #4 /home/eleganta/public_html/catalog/model/payment/mollie/base.php(133): ModelPaymentMollieBase->getAPIClient() #5 /home/eleganta/public_html/vqmod/vqcache/vq2-system_storage_modification_system_en in /home/eleganta/public_html/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 39

**Comment by QualityWorks** [comment]
there should be a check in the code to avoid this.
Can we receive admin and ftp credentials on support.mollie@qualityworks.eu so we can have a look at what's happening?
