### ISSUE TITLE
undefined function _PhpScoper5f491826ce6ce\GuzzleHttp

### ISSUE THREAD

**Issue by shiftukaz21** [mollie/OpenCart#259]
For a week now I have not been able to receive payments through your service, and the support service does not even think to comment on this. I tried to write an e-mail, I created a ticket on the opencart, and now I will try to publish it here for the last time. 

**Do not pay attention that the server is on the local device, the same error is on the hosting server**
**Opencart Version 3.0.3.7 with Journal 3 Template**

Fatal error: Uncaught Error: Call to undefined function _PhpScoper5f491826ce6ce\GuzzleHttp\choose_handler() in C:\xampp\htdocs\catalog\controller\payment\mollie-api-client\vendor\guzzlehttp\guzzle\src\HandlerStack.php:39 Stack trace: #0 C:\xampp\htdocs\catalog\controller\payment\mollie-api-client\vendor\guzzlehttp\guzzle\src\Client.php(64): _PhpScoper5f491826ce6ce\GuzzleHttp\HandlerStack::create() #1 C:\xampp\htdocs\catalog\controller\payment\mollie-api-client\src\MollieApiClient.php(237): _PhpScoper5f491826ce6ce\GuzzleHttp\Client->__construct(Array) #2 C:\xampp\htdocs\catalog\controller\payment\mollie-api-client\helper.php(100): Mollie\Api\MollieApiClient->__construct() #3 C:\xampp\htdocs\admin\controller\payment\mollie\base.php(101): MollieHelper->getAPIClientAdmin(Array) #4 C:\xampp\htdocs\admin\controller\payment\mollie\base.php(1230): ControllerPaymentMollieBase->getAPIClient(0) #5 C:\xampp\htdocs\system\storage\modification\system\engine\action.php(79): ControllerPaymentMollieBase->index() #6 C:\xampp\htdocs\admin\c in C:\xampp\htdocs\catalog\controller\payment\mollie-api-client\vendor\guzzlehttp\guzzle\src\HandlerStack.php on line 39

**Comment by QualityWorks** [comment]
I'm sorry I have not seen a support ticket. Please email is on support.mollie@qualityworks.eu
We can downgrade to v9 4.0 for now. We are also testing v10.2.0 which should definitively fix this issue.
