### ISSUE TITLE
Status page: payment failed (e.g. cancelled)

### ISSUE THREAD

**Issue by msterrek** [mollie/OpenCart#26]
Nadat de bestelling voltooid is (ook het geld op mollie beheer ontvangen is)
Worden de klanten naar de pagina door gestuurd op opnieuw te betalen.
Status page: payment failed (e.g. cancelled)

deze error zie ik in de error log
2015-07-16 20:24:57 - PHP Notice:  Undefined index: custom_field in /htdocs/catalog/controller/checkout/confirm.php on line 166

Wat kan ik hier aan doen?

**Comment by paetor** [comment]
Hi Msterrek. Kan je een mail sturen naar info@mollie.com met dit issue en daarbij ook duidelijk vermelden om welk Mollie-account het hier gaat? Zonder een mollie-account is het voor mij lastig debuggen en ik zou je niet adviseren dat soort informatie hier te delen.
