### ISSUE TITLE
Issue after installing no-email-cancelled-order.ocmod.zip in OpenCart 3.X

### ISSUE THREAD

**Issue by hansleplae** [mollie/OpenCart#261]
Hi Mollie,

I installed this ocmod to avoid sending confirmation mails from opencart when the payment was not successful (as suggested in post https://github.com/mollie/OpenCart/issues/74). This works fine, except for the fact that now also with "free checkout" (the payment is bypassed because the amount is 0 after using a voucher), no confirmation mail is sent. In this case I should expect an email to be sent.

I can clearly link this issue to the ocmod as the email is sent when the modification is disabled

Kind regards,
Hans Leplae

**Comment by QualityWorks** [comment]
Hi Hans,

I assume that the status that the "free checkout" gives is not selected in the list of "processing status" in your store settings
![image](https://user-images.githubusercontent.com/12255644/115876919-2e383180-a447-11eb-9cd3-d008f351ee9c.png)
