### ISSUE TITLE
warning after update

### ISSUE THREAD

**Issue by bosklapperbelg** [mollie/OpenCart#263]
i get "Warning: Mollie Payment Fee order total is disabled!" after update

Dutch >> Waarschuwing: Mollie Payment Fee ordertotaal is uitgeschakeld!

**Comment by ramondunker** [comment]
Volgens mij is dit een nieuwe functie, zie de release:

Added payment fee total

**Comment by QualityWorks** [comment]
klopt, we hebben nu de mogelijkheid toegevoegd om kosten per betaalmethode te rekenen. Hiervoor moet je wel het order total aanzetten. de rest van de instelling gaan via de module.
