### ISSUE TITLE
wrong payment total of mollie on checkout for multistore with multicurrency and decimals=0

### ISSUE THREAD

**Issue by snowbird25** [mollie/OpenCart#266]
Using opencart multi-store with multi-currencies and 0 decimals places for the non-standard currencies to get pretty prices, mollie payment module 10.3.1 still calculates price with 2 decimals and does not use $total which is shown on the checkout confirmation. 

(e.g. total shown on checkout confirmation 85$, mollie uses internal calculations and jumps to the payment with e.g. 85.43$. In comparison, standard opencart Paypal module takes $total and jumps to the paypal payment page with $85). Any suggestions?

**Comment by QualityWorks** [comment]
we have to do internal calculations for other reasons. This is point that I do not think we have tested. We will  have a look at this and update it in the next release

**Comment by snowbird25** [comment]
ok, thank you for the fast reply, we will wait for the next release supporting this special requirement.
