### ISSUE TITLE
Betaalmethode iDEAL toont geen titel op afrekenpagina

### ISSUE THREAD

**Issue by RogierVC** [mollie/OpenCart#269]
Bij Stap 5 in het afrekenproces kan de titel niet gevonden worden vanuit de vertalingen.
OpenCart 2.3.0.2, extensie 10.3.1

`<b>Warning</b>: Illegal string offset 'title' in <b>/public_html/admin/view/template/payment/mollie.tpl</b> on line <b>163</b>s`

![Screenshot_1](https://user-images.githubusercontent.com/34268966/125289870-0064d980-e320-11eb-9695-ca85e94d6534.jpg)

**Comment by nl2ttl** [comment]
Probleem is opgelost, de "foutmelding" is ontstaan bij installatie van de plugin. 

Hierdoor lijkt het dat de webpagina een foutmelding genereerd, maar in werkelijkheid is het veld "Titel bij geavanceerde instellingen" in de plugin bij installatie niet goed gevuld.

Na de titel gezet te hebben naar " iDeal" en de instellingen van de plugin opgeslagen te hebben is alles inorde.

![Mollie2](https://user-images.githubusercontent.com/87672281/129311072-408303ea-b0b4-445b-8980-e2d03d76d8fe.png)
![Mollie1](https://user-images.githubusercontent.com/87672281/129311077-90582ed5-3955-4928-806b-1f7c37138368.png)

**Comment by RogierVC** [comment]
😎
