### ISSUE TITLE
Mollie api client not loaded on git clone or included in the zip file

### ISSUE THREAD

**Issue by wimrademaker** [mollie/OpenCart#27]
When cloning the repo and uploading it to the server I received the message below, apparently the Mollie api isn't in the cloned source code and I didn't find find it in the readme.mdown.
```
Warning: require_once() [function.require-once]: Unable to access /path/to/webspace/public_html/catalog/controller/payment/mollie-api-client/src/Mollie/API/Autoloader.php in /path/to/webspace/public_html/catalog/controller/payment/mollie/helper.php on line 51Warning: require_once(/path/to/webspace/public_html/catalog/controller/payment/mollie-api-client/src/Mollie/API/Autoloader.php) [function.require-once]: failed to open stream: No such file or directory in /path/to/webspace/public_html/catalog/controller/payment/mollie/helper.php on line 51

Fatal error: require_once() [function.require]: Failed opening required '/path/to/webspace/public_html/catalog/controller/payment/mollie-api-client/src/Mollie/API/Autoloader.php' (include_path='.:/usr/local/lib/php') in /path/to/webspace/public_html/catalog/controller/payment/mollie/helper.php on line 51
```
After cloning the src folder from [https://github.com/mollie/mollie-api-php](https://github.com/mollie/mollie-api-php) and merged it in the OpenCart /catalog/controller/payment/mollie-api-client folder the issue seems to be fixed.

**Comment by lvgunst** [comment]
The `mollie-opencart-x.x.x.zip` file on the [release page](https://github.com/mollie/OpenCart/releases) does include the Mollie API client. If you want to use the source code you need to run:

`git submodule init`
`git submodule update`

**Comment by wimrademaker** [comment]
Without the api client the extension will not work so it isn't a matter if someone wants to use the Mollie API client, he needs it to get it running. 

Some additional lines in the readme.mdown would be helpfull to get your customers successfully install your extension.

**Comment by lvgunst** [comment]
Like I said, the download files `mollie-opencart-x.x.x.zip` on the release page does include the Mollie API client.

We point our customers to the release page in our readme (in the install instructions). A normal user does not need to `git clone` the project.
