### ISSUE TITLE
Orderstatus wordt overgeslagen bij OpenCart 3+

### ISSUE THREAD

**Issue by ronn0** [mollie/OpenCart#271]
Goedemorgen,

Is er een reden dat de addOrderHistory niet wordt gebruikt bij een versie hoger dan V2? Hierdoor verliest de plugin wat compatibiliteit met de standaard werkwijze die Open Cart verwacht. 

https://github.com/mollie/OpenCart/blob/master/catalog/controller/payment/mollie/base.php#L1567

Alvast bedankt.

**Comment by QualityWorks** [comment]
"isOpenCart2x" checks for OC >= 2.0

**Comment by ronn0** [comment]
Oops, my bad. Sorry ;-)
