### ISSUE TITLE
Warning: A non-numeric value encountered in /home/xxxxxxx/web/xyzxyz.nl/public_html/system/library/cart/currency.php on line 69

### ISSUE THREAD

**Issue by officeflex** [mollie/OpenCart#272]
I am setting up the mollie payment system on my default opencart 3.0.3.3. (standard theme for now).  It runs under php 7.3.  After installing Mollie I get Warning: A non-numeric value encountered in /home/xxxxxxx/web/xyzxyz.nl/public_html/system/library/cart/currency.php on line 69 (repeated 6 times) above the choices of payment methods.

When I turn of the mollie extention and select another payment option there is no error.  
The website is forced to https and runs smootly without any other errors.  I did switch off automatic currency update.  
The mollie payment system allows me to select payment option and leads me to the payment system, so it works well.
I am not able to find the cause of this error.  Is there anyone who can give a clue? 

Regards,
Ad

**Comment by QualityWorks** [comment]
if you go into the mollie module, and for each payment method hit the gear button and set a minimum and maximum amount (e.g. 0.01 and 99999) the error should be gone.
We have already fixed this for the next release to not give this error if those fields are left empty

**Comment by officeflex** [comment]
Thanks a lot, this was the right solution.  You made my day!
Regards,
Ad
