### ISSUE TITLE
syntaxerror unexpected token / in json

### ISSUE THREAD

**Issue by PeterNashaat** [mollie/OpenCart#273]
Hello
Getting error : ```syntaxerror unexpected token / in json at position 0 parsererror``` after clicking on refund button
the refund is processed, i'm using Mollie extension
steps:
Sales > Orders > Choose order > Refund button
OpenCart Version 3.0.3.6

![Screenshot from 2021-09-13 12-30-24](https://user-images.githubusercontent.com/13523434/133078876-a231ee36-08d0-4dea-b795-c1c19899f565.png)
![Screenshot from 2021-09-13 12-34-51](https://user-images.githubusercontent.com/13523434/133078881-450410b5-e195-4915-af36-73ac8318e1fd.png)

**Comment by QualityWorks** [comment]
speelt dit nogsteeds?
