### ISSUE TITLE
Order heeft status geannuleerd maar is toch betaald

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#274]
Krijg van een klant een order binnen in Opencart staat geannuleerd maar in het mollie dashboard staat betaald.
De klant heeft de order eerst geannuleerd daarna opnieuw betaald wel een ander bedrag omdat ze iets uit het winkelwagentje gegooid heeft.

Mocht je meer info willen hoor dat ik graag.

**Comment by QualityWorks** [comment]
welke checkout gebruik je?

**Comment by telemoes** [comment]
> welke checkout gebruik je?

Journal checkout

**Comment by telemoes** [comment]
Aanvullende informatie. Kan de gehele status niet wijzigen.
Als ik de status naar verzonden zet krijgt hij toch geannuleerd.
