### ISSUE TITLE
Unable to select VQMOD or OCMOD

### ISSUE THREAD

**Issue by SoftwareOnbekend** [mollie/OpenCart#275]
After installing OC 3.0.3.8 installed mollie 10.3.1.

![image](https://user-images.githubusercontent.com/40216653/139296655-50452586-7a2c-46e8-8339-aa6b20cdc197.png)
At every selection I get the following message:

![image](https://user-images.githubusercontent.com/40216653/139296752-6cf4c2bb-43c6-4876-a9ed-e4fd908ae253.png)
 How to fix this?

Thnx.

S.O.

**Comment by SoftwareOnbekend** [comment]
Is there anyone that has the same issue?
This happends when we open the Ideal option after activating the extension as first option to enable.

**Comment by SoftwareOnbekend** [comment]
Clean installation of OC 3.0.08 and Mollie/Opencart version 11.0.0.
When we try to go to the "Mollie-iDEAL" we still get the same error.
Is there somethime we can do to solve this?

**Comment by QualityWorks** [comment]
kan je ons een email sturen op support.mollie@qualityworks.eu, dan kunnen we even meekijken
