### ISSUE TITLE
Plans to create a installable package (OCMod / Events only)?

### ISSUE THREAD

**Issue by osworx** [mollie/OpenCart#281]
While it may fine to have a OCMod and a VQMod version.
Nevertheless, with OC 4.x both will be gone and history.

Using OC 3.x and VQMod should be also avoided (too much overhead and finally useless if developers make their job).

So my questions are: 
1. do you plan to publish a package absed only on events (for OC 4.x)?
2. publish a package which can be installed easily with the integrated installer?

Because - as the readme advice: copy the content from the folder uplaod to .. and so on.
Really "old school"!
And also suitable for all those noobs.
Why not using the infrastructure which already exists?

thx for reading and answering.

**Comment by QualityWorks** [comment]
Yes, we plan to support Oc4 when it comes out. 
We agree vqmod should be avoided on oc3, this is why we have an ocmod version available as well. Vqmod is added for oc1.5 and we do give the option to use vqmod for the other versions as well. But it is either one or the other. 

And we already have an installer in the OpenCart marketplace. Very new school.

So we do already use the infrastructure available. But as you know, the ocmod installer in 3.0 is limited and would force us to place files in extension folder where they don't belong. So using the installer or not using it will be a compromise either way.

This is the most effective way for us to support Oc1.5 - 3.x  and not having to manage 4 versions of the module.
