### ISSUE TITLE
v.11.0.1: Useless tags and code in xml

### ISSUE THREAD

**Issue by osworx** [mollie/OpenCart#282]
Making a installable package of your extension (for OC 3.x), unfortunetaly I see a lot of useless tags and code inside the current **mollie.ocmod.xml_**
For example OCMod does not use **replace** tags in the `<search>..</search>`

Then, **german** and/or **english** is not a valid language.
Use only the 2-2 letter codes, e.g. de-de or en-gb

I know that such code parts a skipped, but why having them when not supported??

And finally, why so much code in the xml?
All those lines could be easely "outsourced" to external files which are called then by (e.g.) `$this->load->controller( 'mycontroller', $array );`

Would make the xml 99% smaller (and easier to handle/update).

**Comment by QualityWorks** [comment]
We already have an installer available in the OpenCart marketplace.

And as usual you seem to criticize without asking for background . German and English are valid for oc1.5, a version we still support.

**Comment by osworx** [comment]
> German

was never a valid language package!
It was for OC 1.5.c **de-DE**

And I know what I am saying, providing German language packages since 11 years.

**Comment by QualityWorks** [comment]
How about English and all other languages? In oc1.5, the folder could technically be named anything, and convention was to name it the language name.
So you're saying that YOU didn't follow the oc1.5 standard for german

**Comment by osworx** [comment]
> We already have an installer available in the OpenCart marketplace.

Great - could you state here also.
And why is a facebook extension linked to the mollie extension( https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31135 ) - if this is the correct and "official"

How to Start with the Mollie for OpenCart plugin
Getting started with Mollie for OpenCart is easy and fast. Follow the following 4 steps and you can start receiving payments in no-time:

    1. Download plugin >> here (here is https://www.opencart.com/index.php?route=marketplace/download&extension_id=32336 which is a fb extension)

See also no OC version there greater than 3.0.3.3 .. but 4.x which still not published.

Or do you have another "official" downloadable extension using the installer?

**Comment by QualityWorks** [comment]
I don't know what Facebook extension you're talking about. We are developer not Mollie, we don't do marketing.
On version support, I will check.
