### ISSUE TITLE
Illigal string offset title

### ISSUE THREAD

**Issue by nebur634** [mollie/OpenCart#285]
Warning: Illegal string offset 'title' in /home/.../htdocs/catalog/model/payment/mollie/base.php on line 238

Causing no title or just a single letter to be shown as payment method....

Mollie Opencart 11.0.1
Opencart 3.2.0.1

**Comment by QualityWorks** [comment]
can you please email us with admin and ftp access so we can have a look for you? support.mollie@qualityworks.eu
