### ISSUE TITLE
Bancontact issue guest user

### ISSUE THREAD

**Issue by MabadosS** [mollie/OpenCart#286]
Issue with bancontact. Only occurs as guest user cancels the payment and wants to retry. Does not occure with logged in users who cancel the payment and hit retry.

Opencart 2.3.0.2
Mollie: mollie-11.0.1

Error code:
Notice: Undefined index: customer_group_id in /home/xxxxx/xxxxxxx/catalog/model/payment/invoicepay.php on line 17

Screenshot at https://paste.pics/591e50ca617a047b07a74e3430a3fd6b

**Comment by MabadosS** [comment]
Edit: Error also occurs when cancelling other payment methods

**Comment by QualityWorks** [comment]
This Notice is in invoicepay, this file is not part of the mollie module
Notice: Undefined index: customer_group_id in /home/xxxxx/xxxxxxx/catalog/model/payment/invoicepay.php on line 17
