### ISSUE TITLE
Refunds gone in orders / Terugbetalingen verdwenen vanuit orders

### ISSUE THREAD

**Issue by KaleStud** [mollie/OpenCart#289]
We used to be able to (partially or completely) refund orders by opening an order on the (admin-)backend, 
Since two versions now, these buttons have disappeared. (Mollie, Opencart 2.3.0.2).
The webhook would still be intact though?!

Het was mogelijk om (geheel of gedeeltelijk) een terugbetaling te doen door in de backend (admin) een bestelling te openen.
Sinds de laatste twee versies zijn de knoppen hiervoor verdwenen. (Mollie, Opencart 2.3.0.2)
De webhook lijkt me echter nog wel te bestaan, toch?

**Comment by QualityWorks** [comment]
This function has not been removed, But moved and expanded. It can be found in the "mollie" tab on the bottom of the order page
![image](https://user-images.githubusercontent.com/12255644/161996737-6704d4a2-e19e-47b0-a57d-473278f8e8b1.png)
