### ISSUE TITLE
Cadeaucheques Monizze en Sodexo werken niet bij het afrekenen

### ISSUE THREAD

**Issue by Nathan-DC** [mollie/OpenCart#291]
Hallo,

Wij hebben cadeaucheques van Monizze en Sodexo ongeveer meer dan een week geactiveerd met de contractnummers van beide. 
In opencart 3.0.3.8 met Journal 3.1.12 staat alles geactiveerd.
Bij het afrekenen krijgen wij de melding: **Er is een fout opgetreden bij het opzetten van de betaling**
Hij gaat wat je ook doet nooit over naar het betaalscherm, ondanks alles is ingesteld. Deze is ingesteld op enkel cadeaucheques te ontvangen. Deze heeft nooit gewerkt vanaf de datum van activatie.

Alsook is er een vertaalfout bij betalingsdetails die de taal van het volgende niet weergeeft: **text_issuer_voucher:** (getest in het Nederlands en Engels)

Alvast bedankt

**Comment by QualityWorks** [comment]
We zullen dit nakijken en fixen voor de volgende release
