### ISSUE TITLE
Notice: Undefined property: Proxy::getMolliePayments

### ISSUE THREAD

**Issue by telemoes** [mollie/OpenCart#293]
Na de update krijg ik deze melding als ik een bestelling wil bekijken.
> Notice: Undefined property: Proxy::getMolliePayments

Verder een wit scherm met verder niks, betalingen werken gewoon kan ze alleen niet bekijken.
Graag zsm een oplossing.

**Comment by telemoes** [comment]
Zou je er naar kunnen kijken kan nu geen orders afvinken en bekijken in het admin

vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php on line 51

**Comment by ydebing** [comment]
Zelfde probleem hier! Bestellingen ouder dan 1 dag kunnen niet geopend worden, tenzij ze met PayPal betaald zijn. Wit scherm of HTTP 500 ERROR.

Een snelle oplossing zou erg geapprecieerd worden. Alvast bedankt!

**Comment by telemoes** [comment]
Vandaag gedowngrade naar een eerdere versie helaas ging dat ook niet goed.
We kunnen in het admin orders nu dus niet op verzenden zetten en komen daardoor ook niet bij mollie als verzonden aan dat moet nu handmatig. Graag een snelle oplossing.

**Comment by QualityWorks** [comment]
Dit is als de installatie van de nieuwste versie niet helemaal goed gegaan is, zorg dat de oude  system/mollie.ocmod.xml of de oude vqmod/xml/mollie.xml verwijderd zijn en vervangen door de nieuwe.
