### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by vikingvoorhees** [mollie/OpenCart#297]
Hi there. apologies i have no tech experience. i've installed the mollie extension. also when i hit install, i get an error page. But when i refresh and go back to the payments list. Mollie is there and installed. when i go to edit it. it opens up but shows a Page not found message at the top to the left of the admin dashboard and a message saying The page you are looking for could not be found! Please contact your administrator if the problem persists.

Im using opencart 2.1.0.1

**Comment by QualityWorks** [comment]
can you please email us at support.mollie@qualityworks.eu we can have a look for you
