### ISSUE TITLE
Shipping zone error present with old accounts 

### ISSUE THREAD

**Issue by AmyAtMollie** [mollie/OpenCart#298]
Hello QualityWorks,

The merchant was still reproducing the error after updating to 11.1. We tested the issue from both of our sides and it appears the issue is occurring with registered accounts that were created a long time ago. What we think is happening is that the time these accounts were created, the 'regio/provincie' field wasnt recquired yet and so it was never stored in their address details. The checkout still does a check of this field and throws an error for these older accounts.
When I tested with an unregistered account I did not get the shipping zone error. When I made a new account I did not get the error either. For the merchant with an old account, they are getting this error.
Is this issue known and will there be a fix for it? 

Original issue that was closed: Merchant has provided additional information in this thread: 

https://github.com/mollie/OpenCart/issues/295

**Comment by QualityWorks** [comment]
The fix in 11.1.1 needs a fix, we have it fixed in the next release

**Comment by AmyAtMollie** [comment]
thank you! Do you have an approximate date when the fix will be released?

**Comment by QualityWorks** [comment]
We're looking at this week

Op ma 30 mei 2022 09:07 schreef AmyAtMollie ***@***.***>:
