### ISSUE TITLE
Customers has problem finding the payment

### ISSUE THREAD

**Issue by filipburman** [mollie/OpenCart#30]
Hello,
I have customers not knowing what happens, they can't find how to pay, or being scare off.

When you'r on step 5. and press "Verder" the page jumps to the top. This is very strange for customers.

Then they have to scroll all the way down through the page. And off course then it feels like you have done something wrong. 

Then when you come down to the bottom you see step 6. 

It's really a problem for customers when it jumps up to the top of the page. Why is it doing this, and can it be fixed some way?
![1](https://cloud.githubusercontent.com/assets/9830505/11781236/abb08130-a268-11e5-9595-aeb8d6eea875.png)

![2](https://cloud.githubusercontent.com/assets/9830505/11781240/b177e432-a268-11e5-9fd2-eec856d0cf57.png)

![3](https://cloud.githubusercontent.com/assets/9830505/11781244/b59d2c34-a268-11e5-9322-0073e1044ef1.png)

**Comment by lvgunst** [comment]
Hi @filipburman,
Thanks for reporting this issue. We will try to find a solution.

**Comment by lvgunst** [comment]
Hi @filipburman,

After you click "Verder" in step 5 the form is submitted and the page changes. It is normal behaviour that the page will jump to the top, our plugin can not change this. If you like to have a different user experience you should try a different cart plugin like Quick Checkout http://www.opencart.com/index.php?route=extension/extension/info&extension_id=7382 where to page will not reload.

**Comment by steinvermeulen** [comment]
Hi @lvgunst,

Can I change the page/checkout so I can "confirm" the order on step 5 => so they will be redirected to mollie after step 5?

The extention is very expensive and would like to have a free solution for this.

Thanks for helping out,

Kr,
Stein
