### ISSUE TITLE
The method Apple Pay disappears

### ISSUE THREAD

**Issue by FarahmandM** [mollie/OpenCart#300]
Hello,

I'm using the version 11.1.1 and activated the payment method "Apple Pay". It appears on the checkout page for the first time (with a new browser profile). But disappears after page refresh or change in methods, address etc. Please check it out.

### Technical Info:

**file:** vqmod/xml/mollie.xml
```
$this->document->addScript('catalog/view/javascript/mollie.js');
```

**file:** catalog/view/javascript/mollie.js
```
$(document).ready(function() {
	if (!window.ApplePaySession || !ApplePaySession.canMakePayments()) {
		// Apple Pay is not available
		$.ajax({
			type: "POST",
			url: 'index.php?route=payment/mollie/base/setApplePaySession',
			data: "apple_pay=0",
			success: function() {			
			}
		});
	}
});
```
`window.ApplePaySession` is not defined! So the ajax is called.

**file:** catalog/controller/payment/mollie/base.php
```
public function setApplePaySession() {
    $this->session->data['applePay'] = isset($this->request->post['apple_pay']) ? $this->request->post['apple_pay'] : 0;
    sleep(1);

    return true;
}
```

**file:** catalog/model/payment/mollie/base.php
```
// Return nothing if ApplePay is not available
if(static::MODULE_NAME == 'applepay') {
	if(isset($this->session->data['applePay']) && ($this->session->data['applePay'] == 0)) {
		return NULL;
	}
}
```

**Comment by QualityWorks** [comment]
are you using a one page checkout? If so, which one? We are unable to reproduce this issue on the default checkout

**Comment by FarahmandM** [comment]
Well, currently, we don't use ApplePay. This is what I remember: the ApplePay payment hadn't worked on core OC checkout and also on Journal2 quickchekout.

But there could be something wrong with the response of this Http POST call:

`https://api.mollie.com/v2/wallets/applepay/sessions`

so it could be a setting or an approval, etc., I guess. I think the issue can be closed.
