### ISSUE TITLE
Fatal error DB exception when upgrading to v11.1.1. can't configure the plugin

### ISSUE THREAD

**Issue by jponabehere** [mollie/OpenCart#301]
Fatal error: Uncaught Exception: Error: Duplicate entry " for key 'transaction_id’<br />Error No: 1062<br >ALTER TABLE 'mgu_mollie_payments' DROP PRIMARY KEY, ADD PRIMARY KEY (mollie_order_id, transaction_id) in
/home/barefootsos/public_html/mygreenuniverse.eu/system/library/db/mysqli.php:40 Stack trace: #0 /home/barefootsos/public_html/mygreenuniverse.eu/system/library/db.php(45): DB\MySQLi->query('ALTER TABLE 'mg...') #1
/home/barefootsos/public_html/mygreenuniverse.eu/admin/controller/payment/mollie/base.php(248):DB->query('ALTER TABLE 'mg...') #2 /home/barefootsos/public_html/mygreenuniverse.eu/admin/controller/payment/mollie/base.php(741): ControllerPaymentMollieBase->install() #3
/home/barefootsos/public_html/mygreenuniverse.eu/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(79): ControllerPaymentMollieBase->index() #4 /home/barefootsos/public_html/mygreenuniverse.eu/admin/controller/startup/router.php(26): Action->execute(Object(Registry), Array) #5 /home/barefootsos/public_html/mygreenuni in /home/barefootsos/public_html/mygreenuniverse.eu/system/library/db/mysqli.php on line 40

**Comment by QualityWorks** [comment]
this is because there are very old payments in the database without a "transaction_id"
We will create a fix in the next update to fix this for users where this happens.
For now, you can remove these entries in the database, or you can add a random id in the transaction_id column for these entries

**Comment by jponabehere** [comment]
Great! and thank you for your quick response!
