### ISSUE TITLE
Mollie voucher (Monizze & Sodexo) doesn't show up in payment list.

### ISSUE THREAD

**Issue by Nathan-DC** [mollie/OpenCart#304]
With the new update (11.2.0) we tested and activated the module Mollie Voucher again and it doesn't show up in the list of payments.

(bug in previous version was that you didn't go to the payment page of Monizze or Sodexo, but it was on the list when activated)

OC 3.0.3.8 - Journal 3.1.12

**Comment by QualityWorks** [comment]
![image](https://user-images.githubusercontent.com/12255644/186756510-316f3b19-a23a-443b-b742-62a4c512b4d3.png)
It's still there

and on the product page you can set what voucher category the product is. This will enable the option in checkout too.
![image](https://user-images.githubusercontent.com/12255644/186756963-b4810447-c921-4111-893e-ae94199122ae.png)

**Comment by Nathan-DC** [comment]
Ok, great. Didn't see that and it makes perfectly sense. Thank you!
