### ISSUE TITLE
Fatal error with viewing the order

### ISSUE THREAD

**Issue by rootje123** [mollie/OpenCart#305]
Fatal error: Uncaught Error: Call to undefined method MollieHelper::generateAccessToken() in /
home/customer/www/exmailorder.nl/public_html/oecradmo/storage/modification/admin/
controller/sale/order.php:1545 Stack trace: #0 /home/customer/www/exmailorder.nl/public_html/
oecradmo/storage/modification/system/engine/action.php(79): ControllerSaleOrder->info() #1 /
home/customer/www/exmailorder.nl/public_html/shop/admin/controller/startup/router.php(26): 
Action->execute(Object(Registry), Array) #2 /home/customer/www/exmailorder.nl/public_html/
oecradmo/storage/modification/system/engine/action.php(79): ControllerStartupRouter->index() 
#3 /home/customer/www/exmailorder.nl/public_html/shop/system/engine/router.php(67):
Action->execute(Object(Registry)) #4 /home/customer/www/exmailorder.nl/public_html/shop/
system/engine/router.php(56): Router->execute(Object(Action)) #5 /home/customer/www/
[exmailorder.nl/public_html/shop/system/framework.php(169):](http://exmailorder.nl/public_html/shop/system/framework.php(169):) Router->dispatch(Object(Action), 
Object(Action)) #6 /home/customer/www/exmailorder.nl/pu in /home/customer/www/
[exmailorder.nl/public_html/oecradmo/storage/modification/admin/controller/sale/order.php](http://exmailorder.nl/public_html/oecradmo/storage/modification/admin/controller/sale/order.php) on 
line 1545

**Comment by QualityWorks** [comment]
please try to download and reinstall the module via ftp. it seems like some files aren't updated correctly
