### ISSUE TITLE
Google Chrome auto-fill (login) overwrites API key in Mollie Opencart back-end

### ISSUE THREAD

**Issue by dhuit90** [mollie/OpenCart#306]
In the Settings tab for the Mollie Opencart extension the API Key field has a password value. 
Because of this the Google Chrome passwordmanager will auto-fill the admin password of the Opencart installation in this field. 

The Mollie extension then automatically checks the changed API key (which of course is now invalid) breaking the Mollie module

![autofill-mollie-chrome](https://user-images.githubusercontent.com/52655802/192964977-59abee0a-9996-48d9-94fc-d05c50249b97.JPG)

**Comment by QualityWorks** [comment]
not sure we can do anything about this. the field name is clearly different than the login password field.
I think this is because the "type" is password. It's more a chrome password manager bug than a Mollie module bug.
We'll google some more on this
