### ISSUE TITLE
Mollie together with reverse charge VAT extension

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [mollie/OpenCart#307]
Hi

I have developed a EU Vat Compliant extension https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=25233 and for a client that uses Mollie as payment provider I made a few changes in the base.php.

See attachment for base.php and grep on 'Open Web Creations'.
[base.php.txt](https://github.com/mollie/OpenCart/files/9798830/base.php.txt)

I was wondering, I have made an ocmod file for it, but maybe there is a better solution for it.
The tax in order product data I already make it zero, but the tax on shipping fee or other totals I cant make it zero.

On line 170, if vat must be zero, I added some code to empty the tax rate list.

Added also ocmod file. [EU-VAT-Compliant-Mollie-v1.0-for-OC3.x-ocmod.zip](https://github.com/mollie/OpenCart/files/9798822/EU-VAT-Compliant-Mollie-v1.0-for-OC3.x-ocmod.zip)

Best regards
Dennis

**Comment by QualityWorks** [comment]
Without seeing your entire module, I don't really understand what you're doing and why.
I also don't really understand your question?
And thirdly, I don't understand why a mod would be needed for EU VAT at all. We also have a module for this which doesn't require modding of any payment method.

Anyway, to better understand your need, please email info@qualityworks.eu
