### ISSUE TITLE
Order cancelled - then proceeded with different order count, same order number but stays as cancelled

### ISSUE THREAD

**Issue by ThaDaVos** [mollie/OpenCart#308]
Issue written in English, but can be responded in Dutch too

**In short:**

1. Cancelled orders don't seem to be updated, even though the ideal went through on a second time
2. No emails sent if the order went through after trying a second time
3. Mail being sent for cancelled orders looks a lot like successful orders

**In long:**

We're running into an issue on one of our customers Opencart shops - it uses Opencart version 2.1.0.2.

![afbeelding](https://user-images.githubusercontent.com/5251028/208236346-c7cf4fbb-1fb2-4b32-abda-8efeb4440086.png)

As can be seen in above image, it was first set to cancelled due to the order being cancelled by the user, it even sent mail to the user and shop owner for this - it seems right after that the user continued the onder for a lower amount (take it from me, hid it in the image on request of the shop owner). It all happened on the same day...

Now the issue, the order is still shown as cancelled - even though it's set to paid as shown below:

![afbeelding](https://user-images.githubusercontent.com/5251028/208236437-134a10a9-54e7-49d5-a66d-8979dcdcb10d.png)
![afbeelding](https://user-images.githubusercontent.com/5251028/208236458-5df5613b-d81c-456d-995a-dd3301462165.png)

As can be seen, the order isn't updated to paid and no email was sent to the customer and shop owner - so yesterday the shop owner got a mail from the customer that they didn't receive their order yet even though they paid - the shop owner did get a mail from Mollie though for the correct amount being received for the order - but due the order not being set to paid etc some confusion happened.

**Comment by QualityWorks** [comment]
That should have been a new order with a new order ID. are you using some form of checkout module?

**Comment by ThaDaVos** [comment]
Don't really know - we takeover the shop and are only maintaining it for the customer - what would be the best way to check?

**Comment by QualityWorks** [comment]
can you email us on info@quailtyworks.eu ? we'll have a look for you

**Comment by ThaDaVos** [comment]
> 

Email what exactly?

**Comment by ThaDaVos** [comment]
![Failed order](https://user-images.githubusercontent.com/5251028/220073732-748278cc-717b-41ec-b9ee-b216938fbca9.png)

We had another one happen... it's first canceled and then paid - it seems the customer cancels the order first, changes it and then pays for it - but like you said, it doesn't create a new order, it updates the original one but wrongly

@QualityWorks-Dev  - what do you want me to mail you about?

**Comment by QualityWorks** [comment]
about this issue.
At least in part, it does not seem to be a Mollie issue, but a session / checkout issue in your shop.

**Comment by ThaDaVos** [comment]
I'll mail you about it as requested

**Comment by ThaDaVos** [comment]
I am getting an error when trying to mail the given email adres - are you sure it's correct?

**Comment by QualityWorks** [comment]
sorry, typo info@qualityworks.eu

**Comment by ThaDaVos** [comment]
Yeah I just saw - went to the website and copied it from there

**Comment by ThaDaVos** [comment]
> sorry, typo [info@qualityworks.eu](mailto:info@qualityworks.eu)

I mailed @QualityWorks but never had a response and the customer complains about the issue again - just updated the module to 12.0.0 - hopefully the fix is in there

**Comment by QualityWorks** [comment]
Just an FYI (way too late, I'm sorry). This seems to be caused by the checkout, specifically older Journal themes. Updating Journal should fix it.
