### ISSUE TITLE
PHP Version 8. ?

### ISSUE THREAD

**Issue by BasicMr** [mollie/OpenCart#309]
Can you please tell us when we can use PHP 8.+ ?

Thanks,

Erik

**Comment by gdegraaf** [comment]
I would like to ask this question for php 8.2

**Comment by CoyoteNLD** [comment]
Any chance Mollie will be compatible with OC 3.0.3.9 and PHP 8.2 ? Especially in combination of Journal Theme 3.1.13.

**Comment by gdegraaf** [comment]
> Any chance Mollie will be compatible with OC 3.0.3.9 and PHP 8.2 ? Especially in combination of Journal Theme 3.1.13.

Upvote for this one

**Comment by QualityWorks** [comment]
Module 13.0.0 supports PHP8.2
