### ISSUE TITLE
Additional text for payment details

### ISSUE THREAD

**Issue by takeoffx** [mollie/OpenCart#31]
Hello, 

what would be the best way to add additional information on the cart when checking out? 

Example: After submitting the order below you will be redirected to the payment page.
(like you have with offline transfer, cheque etc.)

![screen shot 2015-12-30 at 14 01 59](https://cloud.githubusercontent.com/assets/11059290/12051045/13b824da-aefe-11e5-9f4a-f4feb67c5ebc.png)

My apologies if this has been discussed already.

Thanks in advanced.

**Comment by takeoffx** [comment]
nothing?

**Comment by RickWong** [comment]
Hi @takeoffx, please send any questions to info@mollie.com. They will be answered there. I will close this GitHub issue.
