### ISSUE TITLE
Error checkout page Unknown: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated 

### ISSUE THREAD

**Issue by gdegraaf** [mollie/OpenCart#311]
On php 8.1 using Journal theme an error appears on the checkout page in the 'Payment details' section.

Unknown: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /public/catalog/controller/payment/mollie/base.php on line 296

**Comment by QualityWorks** [comment]
what version of OC? We only support PHP8 on OC4 at this moment.

**Comment by CoyoteNLD** [comment]
OC 3.0.3.9 will be compatible with PHP 8.2, please release a new version of Mollie for OC 3.x.x.x with PHP 8.2 support.

**Comment by gdegraaf** [comment]
> OC 3.0.3.9 will be compatible with PHP 8.2, please release a new version of Mollie for OC 3.x.x.x with PHP 8.2 support.

That would be great.

**Comment by QualityWorks** [comment]
This issue has been fixed in version 13.0.0 and this should work on PHP8.2
