### ISSUE TITLE
PHP Unknown:  Creation of dynamic property MollieHelper::$db is deprecated

### ISSUE THREAD

**Issue by CoyoteNLD** [mollie/OpenCart#315]
After upgrading to V13.0, I got this error :
PHP Unknown:  Creation of dynamic property MollieHelper::$db is deprecated in .../..../system/library/mollie/helper.php on line 68

Anyone got this problem too? Looks like an incompatible PHP 8.2 command ?
Did re-upgrade OpenCart, cleared Storage folder and refreshed modifications. Issue still exists

OpenCart V3.0.3.9
PHP 8.2
Mollie V13.0.0 (upgraded within O.C. from V12.0.0)

**Comment by BasicMr** [comment]
Same here..

**Comment by gdegraaf** [comment]
+1

**Comment by gdegraaf** [comment]
As a workaround you can add the following on line 4 of .../..../system/library/mollie/helper.php

`/**
 * Use the fully-qualified AllowDynamicProperties, otherwise the #[AllowDynamicProperties] attribute on "MyClass" WILL NOT WORK.
 */
//use \AllowDynamicProperties;

#[AllowDynamicProperties]`

**Comment by dennisb1** [comment]
+1
