### ISSUE TITLE
undefined index "tag_name"

### ISSUE THREAD

**Issue by BeaverUI** [mollie/OpenCart#317]
Hi,

Since the latest update from 13.0.0 to 13.1.0 I get this error in the logs:

2024-03-14 11:20:44 - PHP Notice:  Undefined index: tag_name in admin/controller/payment/mollie/base.php on line 1578
2024-03-14 11:20:44 - PHP Notice:  Undefined index: tag_name in admin/controller/payment/mollie/base.php on line 1581

I updated the plugin from the dashboard, and after I found these errors I manually re-uploaded the latest release, but this didn't change anything.

It appears this notice comes from the online version check routine. I also noticed the version number in my extension catalog hasn't changed: it still reports mollie v13.0.0, even though I cleared the cache, refreshed the modifications through the OpenCart dashboard, and re-uploaded all plugin files manually.

**Comment by dennisb1** [comment]
It's related to #318 
This is a combination of both.

**Comment by QualityWorks** [comment]
the tag_name notice had been fixed partially in 13.1.0, but we missed a spot. Has been updated in 13.1.1
