### ISSUE TITLE
The 'phone' field should contain a valid phone number, in E.164 format. 

### ISSUE THREAD

**Issue by BasicMr** [mollie/OpenCart#318]
After updating to 13.1.0 We receive this error.

Error executing API call (422: Unprocessable Entity): The 'phone' field should contain a valid phone number, in E.164 format. Documentation: https://docs.mollie.com/overview/handling-errors.

**Comment by dennisb1** [comment]
Same issue here.... Opencart 3.0.3.9 and PHP 8.2
Have missed a total day of orders before we notice this....

Doing a rollback now... missed over 20 orders because of this :(

**Comment by QualityWorks** [comment]
we just removed this field from being submitted to Mollie, as it is only required for one of the upcoming releases. 
We'll properly fix it with E.164 once we need to send this info in a next release
