### ISSUE TITLE
Problem with Rabobank

### ISSUE THREAD

**Issue by filipburman** [mollie/OpenCart#32]
Hello,

I don't really know where this issue might be. But I have had multiple customers that have had problems paying with iDeal and Rabobank on their phones. First I have customers that saying they can't connect to their mobile app. And now I had one customer who was returned to the error page. That something didn't go right with the payment. Even though everything was ok? And the payment went through!

Someone else who have had problems with Rabobank?

**Comment by filipburman** [comment]
Now I had another customer, but this time with ING. Same thing happend here. Error message, "Uw betaling is niet voltooid". Even though everything is ok.

**Comment by RicardoJ** [comment]
Hello Filip,

Due to the nature of sensitive information. I'd like to ask to e-mail the transaction information to info@mollie.com so we can investigate what went wrong.

Thank you.
