### ISSUE TITLE
Not working with big orders

### ISSUE THREAD

**Issue by twdre** [mollie/OpenCart#324]
Small orders (less then 25 products or so) are working.
Yesterday a big order with 300+ products it goes wrong.

He tried to change the payment methode also from mollie to bank transfer - Not Working it goes automaticly back to ideal

Keeps telling that the customers details ar not correct
And keeps telling that the privacy policy is not checked.

It was working with mollie 10.1.1

Versions used for website:
Opencart 3.0.3.8
Theme  Journall 3 
Mollie 13.2.0

**Comment by QualityWorks** [comment]
I will assume this is a new website? Have you checked that max_input_vars on the server is high enough? It seems like a veriables limit to me.

**Comment by twdre** [comment]
Hi thank you very much for your response , Website is running 2 years now.

It was on  1000. I put it on 3000. Dont know what is the best value

**Comment by QualityWorks** [comment]
there's at least 11 variables per product line, and about 30 general variables for each order.
max_input_vars of 3000 seems very low to me if you're planning on selling 300 products in a single order. I would try it on 20000

**Comment by twdre** [comment]
Great ,
Banktransfer loading slow with this many items but its. working again.
Have to wait for iDeal payment again if this also working

Thank you !

**Comment by twdre** [comment]
Hmm its back again with a big order 
Now I get a 504 Gateway Time-out
The server didn't respond in time. ??
