### ISSUE TITLE
naar succes pagina na annuleren ideal betaling.

### ISSUE THREAD

**Issue by jeroenwijers** [mollie/OpenCart#37]
Ls,

Ik ga er zeker induiken maar mijn klant meldt dat als iemand een ideal betaling annuleer deze terugkeert naar de succes pagina terwijl er helemaal geen transactie is..

Enig idee?
We gebruiken zover ik kan zien de laatste versie voor Opencart.

**Comment by RicardoJ** [comment]
Hello Jeroen,

Can you give us your partner ID to investigate the payments that have been made?

Ricardo,
Mollie

**Comment by jeroenwijers** [comment]
Ricardo, 

Seems this has beem solved by the webshoop main
developer. 

Ricardo Jacobs schreef op 2016-06-01 10:50: 

> Hello
Jeroen, 
> 
> Can you give us your partner ID to investigate the
payments that have been made? 
> 
> Ricardo,
> Mollie 
> 
> --
> You are
receiving this because you authored the thread.
> Reply to this email
directly, view it on GitHub [1], or mute the thread [2].




Links:
------
[1]
https://github.com/mollie/OpenCart/issues/37#issuecomment-222918565
[2]
https://github.com/notifications/unsubscribe/ACrtJoqpYo3WZJxJF-y3pUnq_RjwOtR5ks5qHTmrgaJpZM4IHCK7

**Comment by RicardoJ** [comment]
That is good news to hear. It seems in other issues of this module, the same goes on, due to settings at the hosting provider. If anything happens agian, feel free to open a new ticket.
