### ISSUE TITLE
Betaling gelukt, module geeft melding dat het niet gelukt is!

### ISSUE THREAD

**Issue by LarsSnoek** [mollie/OpenCart#38]
Het volgende probleem is hardnekkig in deze module!

Bij elke betalings optie (vooral bij grote bedragen) krijgt de klant de melding op de succes pagina dat de betaling mislukt is terwijl deze wel degelijk gelukt is, de status varieert in sommige gevallen, ene keer voltooid en de andere keer geannuleerd!
Tevens heeft de module het moeilijk met het verwerken van orders met een kortings code of als de klant recht heeft op gratis verzenden!
Bij kleine bedragen met een bestelling zonder extra opties gaat het soms goed!
Hoe is de samenwerking met Ajax Quick Checkout?
Het is trouwens vooral PayPal die de grootste problemen heeft met het bovengenoemde, maar zoals ik al zei, alle opties doen het niet goed!

**Comment by nickdecorte** [comment]
Ik heb inderdaad ook het zelfde probleem waarbij de betaling wel in mollie geregistreerd staat, maar in opencart als geannuleerd.

**Comment by LarsSnoek** [comment]
Al meer dan 4 weken van kasje naar de muur gestuurd zonder resultaat, ik heb het nu door een ander bedrijf laten oplossen die de fout eruit heeft gehaald bij deze module, vraag mij niet hoe want daar heb ik geen kijk op maar was niet goedkoop, hopelijk blijft het nu werken maar de hulp bij deze module van Mollie is niet best!

**Comment by RicardoJ** [comment]
Hello all,

We are currently investigating this issue and will let you know asap. when we have the results.

Ricardo,
Mollie

**Comment by RicardoJ** [comment]
Beste @LarsSnoek. Zou je even contact kunnen opnemen met mij via mijn e-mail; ricardo@mollie.com. Alvast bedankt.

**Comment by takeoffx** [comment]
Hello LarsSnoek,

I've to agree the support from mollie is very poor, not the first issue I've submitted an never head back. 

Could you let me know which company solved the issue for you, I am using the Ajax one page checkout as well and I need a fix, my client has an average of 20 orders a day of which at least 50% get the checkout error.

There might be other iDeal solutions out there I will have to look at as well.

I would appreciate a reply.

Thanks in advanced.

Moritz

**Comment by LarsSnoek** [comment]
Hello,

Our problem was a Clean SEO Url extension, wich removes the index.php out of all url, beside the normal SEO Opencart module, als we used the wrong server to work with Opencart (Varnish)
Those 2 ietem resulted in allot of problems in other modules like Mollie and AQC!
We removed that extension and used a simple version wich only removes the index.php from the home page, also we took a new different server and all out problems where over, also Google has no server problems anymore on our website!

Hope this helps

**Comment by RicardoJ** [comment]
Thank you for your response. I'll use this information to debug problems at other Merchants.

**Comment by LarsSnoek** [comment]
Helaas is het probleem nog steeds niet verholpen zo blijkt, bij sommigen gaat het goed maar net zoveel gaat het mis, van onze kant hebben we er nu alles aan gedaan om het op te lossen, ik hoop dat jullie weldra met een nieuwe versie komen die deze problemen oplost want het kost me inmiddels veel geld!

 

Gr. Lars

 

Van: Ricardo Jacobs [mailto:notifications@github.com] 
Verzonden: donderdag 2 juni 2016 16:00
Aan: mollie/OpenCart <OpenCart@noreply.github.com>
CC: LarsSnoek <lars@nltoys.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mollie/OpenCart] Betaling gelukt, module geeft melding dat het niet gelukt is! (#38)

 

Closed #38 <https://github.com/mollie/OpenCart/issues/38> .
