### ISSUE TITLE
betaling gelukt, module geeft "betaling mislukt" redirect

### ISSUE THREAD

**Issue by takeoffx** [mollie/OpenCart#39]
Ik heb precies het zelfde probleem als hier vermeld: https://github.com/mollie/OpenCart/issues/38

Betaling, geld, word ontvangen maar de klant word doorgestuurd naar de betaling mislukt pagina waar hij opnieuw de betaallink kan klikken. 

Dit gebuurt best vaak.

Alvast bedankt voor support. 

Groeten,
Moritz

**Comment by ndijkstra** [comment]
Hallo Moritz,

Zou je je partner ID kunnen doorgeven? Dan kan ik even kijken wat er aan de hand is.


Met vriendelijke groet,

Nick Dijkstra

**Comment by takeoffx** [comment]
Hallo Nick,

ID: 2182991

Alvast bedankt,
Moritz

**Comment by ndijkstra** [comment]
Hoi Mortiz,

Sorry voor de late reactie. Heb je dit probleem nog steeds?

**Comment by karensarkesijan** [comment]
Ik heb dit ook, hoe kan ik dit oplossen ?!
