### ISSUE TITLE
Why is the order created before payment

### ISSUE THREAD

**Issue by filipburman** [mollie/OpenCart#40]
Dear, first of all we have a lot of people having problem paying with Mister Cash. Don't really know why, but it always seems to happen when they use phones.

But the biggest problem we are having with Mollie is that the order is created even though payment is not  done. I have so many orders that are expired and canceled and every time the stock is getting les and les. With example paypals payment module the order is not made until the payment in complete. And this is the right way opencart should work. 

People are also getting the success e-mail before they even pay.

This BIG issue needs to be solved, It's a hassle for both customers and us.

**Comment by RicardoJ** [comment]
Hello Filip,

Can you give us your partner ID to investigate the payments that have been made?

Ricardo,
Mollie

**Comment by filipburman** [comment]
Hello Ricardo,
Here is our partner id: 1594721

**Comment by RicardoJ** [comment]
Futher contact at support e-mail. Closed issue.
