### ISSUE TITLE
Order confirmation email is sent for canceled/failed payments

### ISSUE THREAD

**Issue by WouterWidgets** [mollie/OpenCart#41]
I placed a few test orders, which I all canceled, but I still received the order confirmation email.
Even though the order confirmation email states that the order will be processed as soon as the payment has been completed, it gives the impression that the payment was successful:

> "Uw bestelling bij [winkel] is succesvol ontvangen en zal worden verwerkt zodra uw betaling bevestigd is".

Is there any way to disable the emails for unsuccessful payments?

This was tested with both 'test' and 'live' API keys.

Regards, Wouter

**Comment by RicardoJ** [comment]
Hello Wouter,

We are currently looking in this issue as these are reported also in #40, #39, #38 and #37. We should take more action with our communication. I'd like to apologize for this.

As soon as I find a solution, i'll release a new version of the module.

Ricardo,
Mollie

**Comment by RicardoJ** [comment]
Hello Wouter,

Can you give us your partner ID to investigate the payments that have been made?

Ricardo,
Mollie

**Comment by Reza-Pasdari** [comment]
Hello Ricknox,

Is there any way to disable these email confirmations? any suggestion?
Thank you!

Regards,
Reza

**Comment by Ricknox** [comment]
Yes @Reza-Pasdari,

On the right side of a issue or pull request you can disable notifications of comments or actions.

See the screenshot I attached:

<img width="296" alt="screen shot 2017-04-14 at 13 22 49" src="https://cloud.githubusercontent.com/assets/15246351/25042094/97377f56-2115-11e7-8dc7-83eabcaea5e5.png">
