### ISSUE TITLE
Ajax Quick Checkout compatibilty broken(already fixed, but needs better implementation)

### ISSUE THREAD

**Issue by LVL91** [mollie/OpenCart#42]
The ajax quick checkout module is not working properly with this version.
The main problem was that it started the payment, even if some important fields where not filled in.
Some validation function for Ajax Quick Checkout was overridden by the payment trigger for this mollie module.

I already got it fixed by reverting this commit:
https://github.com/mollie/OpenCart/commit/56e62e2f16940f5d3792182b66607a61f44489a2 

For this file:
catalog/view/theme/default/template/payment/mollie_checkout_form.tpl

Because I don't want to break compatibility for the Quick Checkout module(not to be confused with the Ajax Quick Checkout module!), I hereby like to tell the main developers about this problem for Ajax Quick Checkout users. I tested it on version 4.2.5 of Ajax Quick Checkout. It might be that for later versions this fix does not work. (of you maybe need to keep the code)

Perhaps you could build some functionality that it checks which module is being used.

**Comment by ndijkstra** [comment]
Hi!

Sorry for the late response. Thank you for your message, we'll check if we can change this in our plugin.
