### ISSUE TITLE
OpenCart 2.3.0.2

### ISSUE THREAD

**Issue by jeroencusters** [mollie/OpenCart#44]
De module lijkt niet compatible te zijn met de meest recente oc versie (2.3.0.2). Installeren lukt wel, maar nadat ik de test api key ingeef, geeft de module de melding 'Toegang geweigerd! U heeft geen toegang tot deze pagina. Neem desnoods contact met ons op.'

Voor ons is het nu nog niet urgent. Betreft een proef installatie om te kijken of de extensies die we gebruiken compatible zijn.

**Comment by Daanvm** [comment]
Hoi Jeroen,

Dit is een foutmelding die uit OpenCart zelf lijkt te komen. Zelf krijg ik deze foutmelding niet, maar misschien dat je wat aan deze info hebt: http://stackoverflow.com/a/21235378/5085588.

Kan je laten weten of dat je probleem oplost?

**Comment by jeroencusters** [comment]
Autorisatie had ik al gecontroleerd. Ik heb nu alle Mollie modules apart 'geinstalleerd' (plus) en nu werkt het wel. Bij de vorige versie was ik gewend dat er maar 1 geinstalleerd hoefde te worden en dat de rest automatisch door Mollie werd geinstalleerd. Werkt dus wel.

**Comment by Daanvm** [comment]
Fijn dat het gelukt is!
Ik zal doorgeven dat dit kennelijk verwarrend is, misschien dat we er iets aan kunnen verbeteren of een melding kunnen toevoegen.

Succes met je website!

**Comment by dazlak** [comment]
@jeroencusters @Daanvm  Ik krijg bij het installeren van bijvoorbeeld Mollie Ideal meteen al te zien dat de toegang is geweigerd, ook na het wijzigen van alle permissions. Enig idee hoe ik het zou kunnen oplossen?

**Comment by Senic** [comment]
Dag @jeroencusters en @Daanvm, ik krijg het zelfde probleem na de installantie van de plugin. 

Ik heb de stappen uitgevoerd zoals beschreven staan readme. Oftewel zipje uit gepakt en alle bestanden op via FTP op de server gezet. 

Nu lees ik dat je ze stuk voor stuk hebt geinstalleerd. Hoe krijg ik dit voor elkaar? En moet ik de oude bestanden allemaal verwijderen? 

alvast bedankt!
