### ISSUE TITLE
Bevestig bestelling button ontbreekt

### ISSUE THREAD

**Issue by dazlak** [mollie/OpenCart#47]
Hoi hoi!

Ben even bezig geweest met mollie op opencart 2.3.0.2., alleen krijg ik bij stap 6 de bevestig bestelling button maar niet te zien. Iemand enig idee hoe ik dit zou kunnen oplossen?

Alvast bedankt en geniet van het lekker weer!
Dazlak

**Comment by ndijkstra** [comment]
Hi!

Helaas is onze plugin nog niet geschikt voor de nieuwste versie (2.3.0). Wij zijn hier mee bezig om te kijken of wij dit zo snel mogelijk kunnen aanpassen. Ik raad je aan om onze GitHub pagina even in de gaten te houden voor de volgende update.

Met vriendelijke groet,
Nick Dijkstra

**Comment by ndijkstra** [comment]
Hallo Marcel,

Wij verwachten binnen enkele dagen een nieuwe versie te kunnen releasen voor OpenCart 2.3.x
