### ISSUE TITLE
Getting white page in admin after enabling mollie/plugin

### ISSUE THREAD

**Issue by bas4554** [mollie/OpenCart#55]
Hi People of Mollie,

Just installed your plugin on opencart 2.3.0.2.
Getting a white page in admin (see attachment).

Can you help me out?
![schermafbeelding 2016-11-02 om 10 02 46](https://cloud.githubusercontent.com/assets/23209979/19922583/8f0ec792-a0e3-11e6-9ddb-a09ce82c02af.png)

**Comment by ndijkstra** [comment]
Hi!

Did you install Release 7.1.0 of our plugin?

**Comment by bas4554** [comment]
Hi Nick,

Thank your for you reaction.
Yes, the latest version, available on GitHub.

**Comment by ndijkstra** [comment]
Is it possible to create an admin account and a FTP account for us?
You can send it to [info@mollie.com](mailto:info@mollie.com) with in the subject my name.

**Comment by bas4554** [comment]
Hi Nick,

Send you the e-mail.

**Comment by ndijkstra** [comment]
Problem solved. Extension mbstring was not enabled on the server.
