### ISSUE TITLE
GET: You do not have permission to access this page, please refer to your system administrator.

### ISSUE THREAD

**Issue by ohdude** [mollie/OpenCart#56]
Sup everyone,

I just installed a new version off opencart 2.3.0.2 and I installed the module.
When I want to save the test key I get a permission error

![mollie](https://cloud.githubusercontent.com/assets/6848396/20266655/73121718-aa77-11e6-836a-2e9d9b2ef396.PNG)

**Comment by ndijkstra** [comment]
Hi!

Did you use the correct version of our plugin for OpenCart 2.3?https://github.com/mollie/OpenCart/releases/tag/v7.1.0

**Comment by ohdude** [comment]
For some reason it was blocked. 
I did a reinstall with the new downloaded plugin and it works fine.
