### ISSUE TITLE
Fatal error: 'Error: Could not load model payment!' 

### ISSUE THREAD

**Issue by Meulenkamp-reclame** [mollie/OpenCart#57]
Opencart geupgrade naar versie 2.3.0.2 

Was best veel werk maar nu blijf ik haken bij deze module, heb versie 7.0.1
Ben de hele avond al bezig maar kom er echt niet uit,

Na winkelwagen doorklikken krijg ik na verzendmethode deze foutcode;

Fatal error: 'Error: Could not load model payment!' 
in /home/warring/domains/fijnelaarzen.nl/public_html/system/storage/modification/system/engine/loader.php:169
Stack trace:
#0 [internal function]: Loader->{closure}(Array, Array)
#1 system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array)
#2 catalog/controller/checkout/payment_method.php(53): Proxy->__call('getMethod', Array)
#3 catalog/controller/checkout/payment_method.php(53): Proxy->getMethod(Array, 27.117552)
#4 [internal function]: ControllerCheckoutPaymentMethod->index()
#5 system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array)
#6 catalog/controller/startup/router.php(25): Action->execute(Object(Registry))
#7 [internal function]: ControllerStartupRouter->index()
#8 system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array)
#9 system/storage/modification/system/engine/front.php(37): Action->execute(Object(Registry))
#10 system/storage/modification/system/engine/front.php(32): Front->execute(Object(Action))
#11 system/framework.php(103): Front->dispatch(Object(Action), Object(Action))
#12 system/startup.php(124): require_once('/home/warring/d...')
#13 index.php(19): start('catalog')
#14 {main}

**Comment by ndijkstra** [comment]
Hallo! Heb je de oude plugin ook compleet verwijderd? Het lijkt erop dat hij daarop vastloopt.

**Comment by Meulenkamp-reclame** [comment]
Hoe doe ik dat? Ik heb de oude plugin gezocht in de mysql en alle velden verwijderd

Maar niet de files verwijderd inderdaad, weet niet welke files ik dan moet verwijderen


Met vriendelijke groet,
Johan Meulenkamp

[cid:image001.png@01D24A27.016E46F0]



Adres


Noorderdiep 364
9521BM Nieuw-Buinen


Telefoon
Mobiel

0599 700 230
06 117 903 48


internet



www.meulenkamp-reclame.nl<http://www.meulenkamp-reclame.nl/>




Van: Nick Dijkstra [mailto:notifications@github.com]
Verzonden: dinsdag 29 november 2016 09:49
Aan: mollie/OpenCart
CC: Johan Meulenkamp; Author
Onderwerp: Re: [mollie/OpenCart] Fatal error: 'Error: Could not load model payment!' (#57)


Hallo! Heb je de oude plugin ook compleet verwijderd? Het lijkt erop dat hij daarop vastloopt.

**Comment by ndijkstra** [comment]
Waar die op vast loopt zijn deze bestanden: https://github.com/mollie/OpenCart/tree/opencart-2.2/catalog/model/payment.

Je kunt in ieder geval deze bestanden verwijderen en dan de nieuwe plugin installeren: https://github.com/mollie/OpenCart/tree/opencart-2.2

**Comment by Meulenkamp-reclame** [comment]
Oke ik krijg nu niet meer de foutcode, heb alles verwijderd en opnieuw geupload

Alleen heb ik nu geen afrekenen button;


[cid:image001.png@01D24A28.6B810310]

Met vriendelijke groet,
Johan Meulenkamp

[cid:image002.png@01D24A28.6B810310]



Adres


Noorderdiep 364
9521BM Nieuw-Buinen


Telefoon
Mobiel

0599 700 230
06 117 903 48


internet



www.meulenkamp-reclame.nl<http://www.meulenkamp-reclame.nl/>




Van: Nick Dijkstra [mailto:notifications@github.com]
Verzonden: dinsdag 29 november 2016 10:01
Aan: mollie/OpenCart
CC: Johan Meulenkamp; Author
Onderwerp: Re: [mollie/OpenCart] Fatal error: 'Error: Could not load model payment!' (#57)


Waar die op vast loopt zijn deze bestanden: https://github.com/mollie/OpenCart/tree/opencart-2.2/catalog/model/payment.

Je kunt in ieder geval deze bestanden verwijderen en dan de nieuwe plugin installeren: https://github.com/mollie/OpenCart/tree/opencart-2.2

**Comment by ndijkstra** [comment]
Het lijkt er dan op dat in een CSS bestand de knop wordt verborgen. Je zou even moeten kijken of je dit uit het CSS bestand kan halen.

**Comment by Meulenkamp-reclame** [comment]
Dat moet lukken, thnx

Met vriendelijke groet,
Johan Meulenkamp

[cid:image001.png@01D24A29.E9281B40]



Adres


Noorderdiep 364
9521BM Nieuw-Buinen


Telefoon
Mobiel

0599 700 230
06 117 903 48


internet



www.meulenkamp-reclame.nl<http://www.meulenkamp-reclame.nl/>




Van: Nick Dijkstra [mailto:notifications@github.com]
Verzonden: dinsdag 29 november 2016 10:12
Aan: mollie/OpenCart
CC: Johan Meulenkamp; Author
Onderwerp: Re: [mollie/OpenCart] Fatal error: 'Error: Could not load model payment!' (#57)


Het lijkt er dan op dat in een CSS bestand de knop wordt verborgen. Je zou even moeten kijken of je dit uit het CSS bestand kan halen.
