### ISSUE TITLE
Assign Geo Zone

### ISSUE THREAD

**Issue by TowerEditions** [mollie/OpenCart#60]
Ik zou graag een GeoZone willen kunnen toewijzen aan de Ideal module zodat klanten buiten Nederland deze betaaloptie niet te zien krijgen. Op dit moment heb ik die optie niet kunnen vinden...

**Comment by QualityWorks** [comment]
nog mooier zou zijn een geo zone per betaaloptie van mollie, dus enkel NL voor ideal, maar wereldwijd voor credit card, etc

**Comment by Buddhalife** [comment]
Wij zouden dit ook graag willen, Geo Zone toewijzing per betaal optie.
Is hier meer over bekend?

**Comment by QualityWorks-Dev** [comment]
Beste @TowerEditions en @Buddhalife,

In de nieuwste versie van de module is deze feature geïmplementeerd.
Helaas is deze versie alleen nog beschikbaar voor OpenCart 3.x, we zijn bezig met een backport. Door de backport zal deze functionaliteit binnenkort ook beschikbaar wordt in oudere versies van OpenCart.
We kunnen nog niet met zekerheid zeggen wanneer deze update beschikbaar is.

Met vriendelijke groet,
Roger

**Comment by youridonatz** [comment]
Juist! OC 1.5.6.4. zou daar ook heel blij mee zijn!

**Comment by youri13pixels** [comment]
Is er al iets meer bekend omtrent deze optie?

**Comment by QualityWorks** [comment]
in de 3.0 versie hebben we dit toegevoegd, we zullen het bij de nieuwe updates van de 2.0 en 1.5 versies ook meenemen.

**Comment by youri13pixels** [comment]
Staan deze al online?

**Comment by QualityWorks** [comment]
de 3.0 wel, de andere nog niet

**Comment by youri13pixels** [comment]
oke, enig idee wanneer de nieuwe update beschikbaar is?

**Comment by youri13pixels** [comment]
Kan niet wachten!! :)))))))

**Comment by QualityWorks-Dev** [comment]
We verwachten deze maand nog de 1.5 backport.
De 2.x backport gaat waarschijnlijk al vandaag of begin volgende week online komen.

**Comment by ThaFridge** [comment]
Mooi dat is goed nieuws!

**Comment by QualityWorks-Dev** [comment]
We hebben zojuist een nieuwe release uitgebracht die alle nieuwste features uitbrengt voor OpenCart 1.5 en 2.x.

De nieuwe versie zal zowel op de [releases pagina](https://github.com/mollie/OpenCart/releases/tag/8.2.0) als op de [OpenCart marketplace](https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31135&filter_search=mollie) te vinden zijn.

Met vriendelijke groet, 
Roger
