### ISSUE TITLE
Ideal betalingen worden als niet gelukt teruggestuurd

### ISSUE THREAD

**Issue by liquidacid** [mollie/OpenCart#62]
In sommige gevallen krijgt de klant te zien dat de Ideal betaling is mislukt met als gevolg dat men de betaling nog een keer doet.

**Comment by jeroencusters** [comment]
+1

**Comment by liquidacid** [comment]
hmm duurt lang. Weten jullie al iets van dit probleem? Als het nog lang gaat duren dan moet er even een mededeling in het annuleringsscherm. Beetje irritant en kostelijk om steeds bestellingen terug te moeten betalen.

**Comment by rtbweb** [comment]
Ja inderdaad hier ook, ben al even aan het zoeken geweest maar zie zo ook de oorzaak niet.

**Comment by JelleG** [comment]
Krijg ook bij iDeal en overboeken de melding dat betaling is mislukt. Online is te lezen dat dit probleem al een tijd bestaat.

Is er een idee wanneer versie 2.3.0.2 wordt ondersteund?

**Comment by rtbweb** [comment]
Ik heb hem nu goed draaiend op 2.3.0.2. Bij mij was het een fout in de instellingen die dat veroorzaakte.

**Comment by JelleG** [comment]
Kan je aangeven welke instellingen niet goed stonden?

**Comment by rtbweb** [comment]
Ik heb de plugin eraf gegooit en deze opnieuw gedownload vanaf de mollie website. Daarne werkte die goed.

**Comment by nsamsin** [comment]
Ik draai op versie versie 2.3.0.2 en krijg ongeacht de betaalvorm (ideal, paypal, bitcoints enz.) na het betalen de melding in OpenCart terug:

"Uw betaling is niet voltooid. Helaas is de betaling mislukt. Klik op onderstaande knop om terug te keren naar het afrekenscherm."

Als ik inlog op het Mollie dashboard dan staan de transacties wel als voltooid/betaald, echter met in de history: "Webhook niet succesvol aangeroepen, statuscode 503"

**Comment by rtbweb** [comment]
Klopt. Deze had ik ook. Je moet in mollie een websiteprofiel aanmaken. Daarna gaat het als volgt. Je doet een betaling in de shop, mollie wil het resultaat van de betaling terug sturen naar je shop. Maar als jou shop niet online staat is dit niet mogelijk. (wat logisch is want mollie weet dan niet waar het heen gestuurd moet) 

Dus zorg dat je shop voor mollie te bereiken is. En dat de url in het mollie dashboard klopt

**Comment by nsamsin** [comment]
Dank voor je reactie. In mijn geval was het profiel inderaad al aangemaakt incl. URL. 

De webshop draaide echter nog in maintanance mode waardoor de mollie webhook geen status terug kon geven aan de OC backend :S

**Comment by liquidacid** [comment]
Hebben jullie ook dat het vrijwel elke keer fout gaat als je kortingscodes gebruikt? Ik ben inmiddels naar een alternatief aan het zoeken. Ik word er namelijk net als mijn klanten een beetje moe van inmiddels gezien er niets gedaan word.

**Comment by ndijkstra** [comment]
Hi @liquidacid,

Dat probleem zit hem waarschijnlijk inderdaad in de kortingscodes. In OpenCart zit een instelling die controleert of de klant fraudeert met de kortingscodes. Als je gaat naar: "Settings" > "Option", kun je "Fraud Order Status" het best op een status zetten die de order gewoon doorlaat.

Het probleem dat de melding komt dat de betaling is mislukt lijken we te hebben gevonden. Het probleem is namelijk niet meer voorgekomen sinds de aanpassing. Deze wijziging gaan we zsm uitbrengen als update.

**Comment by ThaFridge** [comment]
Oh dat is heel mooi! Kan niet wachten op de update.

**Comment by liquidacid** [comment]
Voor de ongeduldigen zoals ik, kijk even onder pull requests. Hier staan de updates van 2 files. Aanpassen en gaan! Zojuist zonder problemen getest.

**Comment by liquidacid** [comment]
Alright, na een aantal dagen gebruiken kom ik er achter dat het soms lijkt opgelost. Ik heb nu toch weer dat de klant een bericht krijgt dat de betaling is mislukt. Maar ditmaal staat in het adminpanel ook dat de betaling is geannuleerd, een status die zonder de database handmatig aan te passen ook niet terug gaat overigens.

**Comment by dennisb1** [comment]
+1

Na lang zoeken wat nou het probleem is vond ik het verband met de kortingscodes die wij meer zijn gaan gebruiken en mollie. Na zoeken kwam ik op deze pagina uit...

Jaja ook ik heb er last van en sta vol verwondering te kijken dat dit na 4 maanden nog niet schijnt opgelost te zijn!!!
Wanneer gaan ze wakker worden en het probleem oplossen??!?!

Ik heb wel gevonden hoe je de order op betaald lan zetten wat liquidacid niet lukt, je moet de hele bestelling wijzigen en opnieuw doorlopen zonder wijzigingen maar pas op het laatst op betaald zetten. 


Maar nogmaals dit kost ons erg veel tijd om alle orders elke dag na te lopen die geannuleerd zijn! Kom met een oplossing!!

**Comment by liquidacid** [comment]
@dennisb1 het kan wel makkelijker maar dat heb ik niet gemeld nog omdat het dan misschien als een workaround gezien wordt en minder prioriteit krijgt. Je kunt de status van de bestelling in je database gewoon aanpassen, dat is een paar seconden werk. 

Als je de files volgens de laatste pullrequest aanpast werkt het voor zover ik merk wel beter maar ik vermijd het gebruik van kortingscodes momenteel gewoon. Toch jammer dat je redelijk vast zit aan een payment provider op een gegeven moment. Er wordt aangegeven dat het een bug is in Opencart en dat je het de fraudecontrole uit moet zetten. Dat kan alleen helaas niet in de laatste versies.

**Comment by tomasmollie** [comment]
@liquidacid @dennisb1 er komt vanuit Mollie binnenkort een volledig nieuwe module voor Opencart. Wij verwachten uiteraard dat de problemen zich daar niet meer voordoen. De versie wordt op het moment getest en zodra deze live kan, zullen wij dit uiteraard op onze Github en bij de huidige gebruikers melden.

**Comment by QualityWorks-Dev** [comment]
Beste @liquidacid en @dennisb1,

Recentelijk is er een nieuwe [versie release](https://github.com/mollie/OpenCart/releases/tag/v7.2.0) geweest die deze problemen zou moeten oplossen, mocht dit niet zo zijn verzoek ik jullie om een nieuwe issue te openen.

Met vriendelijke groet,
Roger
