### ISSUE TITLE
Banconcact betalingen worden als niet gelukt teruggestuurd 

### ISSUE THREAD

**Issue by liquidacid** [mollie/OpenCart#65]
Ook bij banconcact gaat het fout met de betalingen, ook met de update. Zie issue #62 
Ondertussen ga ik opzoek naar een nieuwe payment provider.

**Comment by tomasmollie** [comment]
Hi @liquidacid,

Dat is heel bijzonder. Ik zal met onze Opencart specialist dit probleem z.s.m. oppakken om te verhelpen. Zodra hier meer over bekend is, deel ik dit ook op Github.

**Comment by QualityWorks-Dev** [comment]
Beste @liquidacid,

Onze excuses voor de lange looptijd van dit probleem.
Kunnen we wellicht nog iets voor je betekenen?

Met vriendelijke groet,
Roger
