### ISSUE TITLE
Order confirmation email is sent for cancelled/failed payments

### ISSUE THREAD

**Issue by mangopavlova** [mollie/OpenCart#67]
When testing the module I encounter the issue that when I place orders, for which I then cancel the payment (status: geannuleerd/mislukt), the order confirmation email is still sent to the customer and it gives the impression that the payment was successful which is confusing to the customer:

"Uw bestelling bij [winkel] is succesvol ontvangen en zal worden verwerkt zodra uw betaling bevestigd is".

Is there any way to disable the emails for unsuccessful payments?

This was tested with 'test' API keys,
Opencart v2.1.0.2
mollie release 6.4.1 patched with: https://github.com/mollie/OpenCart/pull/64/files, https://github.com/mollie/OpenCart/pull/63/files

I have noticed this issue was logged previously at: https://github.com/mollie/OpenCart/issues/41, but it is marked closed and I cannot find a solution for it.

Regards,
Marcel

**Comment by QualityWorks-Dev** [comment]
Hi @mangopavlova,

We're sorry this functionality seems confusing to your customers, unfortunately this is opencart default behavior and is not controlled by the mollie module.

You could try to find a solution on the opencart marketplace that fixes this problem for you.

Regards,
Roger

**Comment by mangopavlova** [comment]
If anybody else is having this issue, I've created an ocmod to perform a hard-coded check on order status cancelled or failed before sending the email:
Use it at your own discretion.
Regards,
Marcel

[Opencart check order status id for customer sendmail.ocmod.xml.zip](https://github.com/mollie/OpenCart/files/1208431/Opencart.check.order.status.id.for.customer.sendmail.ocmod.xml.zip)

**Comment by nikeacg** [comment]
@mangopavlova ik heb dit xml bestand geinstalleerd maar OC blijkt nog steeds de confirmation email te sturen bij gecancelde betalingen.
