### ISSUE TITLE
fail on 'edit'

### ISSUE THREAD

**Issue by f3bruary** [mollie/OpenCart#70]
sorry, first time OC user hier.
admin en catalog overgezet, geactiveerd, maar wanneer ik op edit druk:

`Notice: Undefined index: user_token in /www/admin/controller/extension/payment/mollie/base.php on line 201Notice: Undefined index: user_token in /www/admin/controller/extension/payment/mollie/base.php on line 308Notice: Undefined index: user_token in /www/admin/controller/extension/payment/mollie/base.php on line 314Notice: Undefined index: user_token in /www/admin/controller/extension/payment/mollie/base.php on line 320Notice: Undefined index: user_token in /www/admin/controller/extension/payment/mollie/base.php on line 326Notice: Undefined index: user_token in /www/admin/controller/extension/payment/mollie/base.php on line 327Notice: Error: Could not load template /www/admin/view/template/extension/payment/mollie.tpl! in /www/system/storage/modification/system/library/template/php.php on line 23`

**Comment by QualityWorks-Dev** [comment]
Beste @f3bruary,

Kun je aangeven om welke Mollie en OpenCart versie het gaat?

Met vriendelijke groet,
Roger

**Comment by f3bruary** [comment]
d'oh! rsl voor versie 3.X ipv 2.3.X geinstalleerd. Het werkt inmiddels al. tnx!
