### ISSUE TITLE
Fraude status bij coupon

### ISSUE THREAD

**Issue by Wuffz** [mollie/OpenCart#71]
Beste,

Wanneer een coupon zo is ingesteld dat de gebruiker ingelogd moet zijn, word de betaling op de fraudestatus gezet. Dit is alleen het geval wanneer er word betaalt via de Ideal betaalmethode ( en hoogstwaarschijnlijk ook andere Mollie betaalmethoden )

In dit geval betreft het een opencart 2.3.0.2 installatie .

In het bestand /catalog/extension/total/coupon.php Komt de code niet door de volgende statement heen. 
`if ($coupon_query->row['logged'] && !$this->customer->getId()) {
		$status = false;
}`

Vermoedelijk door een callback vanuit Mollie waarin de sessie niet bestaat, en dus de gebruiker niet is ingelogd.

Met vriendelijk groet,

Patrick Roozeboom
( www.designenmedia.nl )

**Comment by QualityWorks-Dev** [comment]
Beste Patrick,

Dit is eigenlijk een opencart issue, maar omdat we toch alles uitgezocht hebben vind je bijgevoegd een ocmod die de total/coupon.php overschrijft waardoor dit probleem niet meer voor zou moeten komen.
**Let op! dit bestand word dus wel overschreven en dit zou eventuele gevolgen kunnen hebben voor andere ocmods m.b.t. coupons**

[coupon-fraude-fix.ocmod.zip](https://github.com/mollie/OpenCart/files/1267284/coupon-fraude-fix.ocmod.zip)


Met vriendelijke groet,
Roger
