### ISSUE TITLE
Can't see payment options in opencart 3.0.2.0

### ISSUE THREAD

**Issue by arnogeismar** [mollie/OpenCart#73]
Config seems to have happened correctly. I see no errors in my error logs (see screenshots)

This is the plugin file from the releases page:
![opencartplugin](https://user-images.githubusercontent.com/4123641/36220327-7afda43c-11ba-11e8-83f5-2c085b11df5f.PNG)

This is the mollie config:
![mollie activated](https://user-images.githubusercontent.com/4123641/36220349-877689a4-11ba-11e8-9bc2-8fc6ea26974a.PNG)

![config](https://user-images.githubusercontent.com/4123641/36220354-8aab9a60-11ba-11e8-876e-fc19d4a12ad7.PNG)

**Comment by QualityWorks** [comment]
heb je ook de geo zone juist ingesteld? kan je de instellingen van het eerste tabblad laten zien?

**Comment by arnogeismar** [comment]
![geozones](https://user-images.githubusercontent.com/4123641/36225349-b1a5bc8a-11ca-11e8-9c75-4acb8c5df1c0.PNG)

**Comment by QualityWorks** [comment]
Hi Arno, Kan je me mailen op info@qualityworks.eu? dan kunnen we je daar verder helpen.

**Comment by printopia** [comment]
Exact hetzelfde probleem. Ook even email gestuurd.

**Comment by digiexpert** [comment]
Is dit probleem al opgelost? Ik loop tegen hetzelfde aan

**Comment by QualityWorks** [comment]
De laatste is opgelost na een herinstallatie van de shop (daar waren meerdere upgrades van Opencart gedaan achter elkaar)
Tot nu toe hebben we niks in de module zelf gevonden wat niet klopt

**Comment by digiexpert** [comment]
Bedankt voor je snelle reactie.

Ik heb een schone shop geïnstalleerd. Ik start er net mee maar ik krijg ze er niet voor helaas

**Comment by QualityWorks** [comment]
Kan je ons een mailtje sturen? Dan gaan we je verder helpen.

On 10 Mar. 2018 19:32, "digiexpert" <notifications@github.com> wrote:

Bedankt voor je snelle reactie.

Ik heb een schone shop geïnstalleerd. Ik start er net mee maar ik krijg ze
er niet voor helaas

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mollie/OpenCart/issues/73#issuecomment-372053231>, or mute
the thread

**Comment by digiexpert** [comment]
Ik heb afgelopen zaterdag een mail gestuurd

**Comment by QualityWorks-Dev** [comment]
we hebben een nieuwe versie uitgebracht, kijk eens bij de releases. Als het goed is wordt het probleem hiermee opgelost.
