### ISSUE TITLE
Order confirmation email is sent for canceled/failed payments to customers and admin

### ISSUE THREAD

**Issue by Lesliegrun** [mollie/OpenCart#74]
Hallo Mollie
ik heb een probleem met jullie extensie voor opencart 3.0.2.0
Opencart 3.0.2.0 stuurt een email naar de klant als hij de bestelling heeft geannuleerd in Mollie
is er een manier dat ik dit uit kan zetten want het is erg verwarrend voor mijn klanten want de mail lijkt erg op de mail van een betaalde bestelling
ik heb ook al de vraag gesteld op het opencart forum zij denken dat het aan uw extensie ligt
https://forum.opencart.com/viewtopic.php?f=202&t=202508&p=715924#p715924
![voorbeeld](https://user-images.githubusercontent.com/36963226/36854592-acf0fda0-1d71-11e8-89a3-a18fde1621b7.png)

Met vriendelijke groet
Leslie

**Comment by QualityWorks** [comment]
het is geen probleem met onze module, maar gelukkig heb ik wel een oplossing voor je.
dit is het probleem:
- bij de checkout wordt een bestelling aangemaakt met status 0
- mollie krijgt antwoord met een update, hier hoort een status bij, hierbij geven we ook aan of de klant een update moet krijgen of niet "notify"
- bij het updaten van een status van 0 naar iets anders stuurt opencart ALTIJD een update naar de klant, ook als deze geannuleerd is; notify wordt in dit geval genegeerd.

Ik heb een kleine mod geschreven die deze check er in zet.
[no-email-cancelled-order.ocmod.zip](https://github.com/mollie/OpenCart/files/1772021/no-email-cancelled-order.ocmod.zip)

**Comment by Lesliegrun** [comment]
Bedankt deze ocmod heeft mij erg goed geholpen ik ben hier al dagen mee bezig
mag ik deze ook delen op het opencart forum ?
Met vriendelijke groet 
Leslie de Groot

**Comment by QualityWorks** [comment]
Ja natuurlijk. Let wel, deze mod is enkel voor 3.x

**Comment by Almack2013** [comment]
Super bedankt voor deze oplossing!
