### ISSUE TITLE
Mollie – KBC/CBC-Betaalknop niet zichtbaar

### ISSUE THREAD

**Issue by ThaFridge** [mollie/OpenCart#75]
Ik krijg Mollie – KBC/CBC-Betaalknop niet actief in opencart 2.3.0.2 zowel als in opencart als in mollie staat het profiel op actief.

**Comment by QualityWorks** [comment]
kan je ons even mailen op info@qualityworks.eu ?

**Comment by ThaFridge** [comment]
Ow ik ben wat te voorbarig geweest, ik heb de bug terug kunnen vinden in plugin Payment-Based Fee/Discount om transactiekosten door te kunnen berekenen. 

Probleem opgelost!
