### ISSUE TITLE
transactiekosten doorberekend aan de klant

### ISSUE THREAD

**Issue by ThaFridge** [mollie/OpenCart#76]
Komt er in de toekomst een mogelijkheid om rechtstreeks vanuit de mollie api kosten door te berekenen aan klant? Op het moment heb ik verschillende webshops in beheer die de percentages van creditkaart en buitenlandse banken en soms ook de transactiekosten door willen bereken. Dit is namelijk nu alleen mogelijk met de module payfront (betaald) en dit werkt vrij omslachtig.

**Comment by willemstuursma** [comment]
Dit staat voorlopig niet op onze roadmap, sorry.
