### ISSUE TITLE
No payment_method returned

### ISSUE THREAD

**Issue by nebur634** [mollie/OpenCart#78]
When paying via iDeal, the payment method is stored as text_title / opencart 2.3.0.1

**Comment by QualityWorks-Dev** [comment]
what version of the Mollie module are you using and what language settings do you have in the store?

**Comment by nebur634** [comment]
Mollie Opencart 8.3.2 and the language is Dutch

**Comment by QualityWorks-Dev** [comment]
can you please email us on info@qualityworks.eu with your store details so we can have a look?

**Comment by livewirerules** [comment]
im having the same issue.. And i have PDF pro installed... Any idea how can i fix this?
