### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Webmedia-Ede** [mollie/OpenCart#79]
Issue

**Comment by QualityWorks-Dev** [comment]
kan je hier iets meer info over geven, zoals wanneer je deze error krijgt, opencart versie, module versie, etc?

**Comment by Webmedia-Ede** [comment]
Beste,

Ik heb de module geupload via de FTP. En het werkt totaal niet. Ik kan evt de FTP en logins van de admin doorgeven?

Mochten er nog vragen of opmerkingen zijn hoor ik deze graag,

Met vriendelijke groet,
Kenneth Wolfs
Eigenaar @ Webmedia - Ede
Tel:  0318 - 727 057

**Comment by QualityWorks-Dev** [comment]
graag, kan je die sturen naar info@qualityworks.eu ?

**Comment by Webmedia-Ede** [comment]
Beste
Hierbij de logingegevens om te kijken

> Admin inlog url: http://www.bedworld <http://www.bedworld/>.nl/V1/admin
> Admin gebruikersnaam: admin	
> Admin wachtwoord: Welkom01!
> 
> FTP server: bedworld.nl <http://bedworld.nl/>	
> FTP poort: 22
> FTP gebruikersnaam: Mollie@bedworld.nl <mailto:Mollie@bedworld.nl>
> FTP wachtwoord: tHPoIxiti


Mochten er nog vragen of opmerkingen zijn hoor ik deze graag,

Met vriendelijke groet,
Kenneth Wolfs
Eigenaar @ Webmedia - Ede
Tel:  0318 - 727 057
