### ISSUE TITLE
erg vaak betaling verlopen melding

### ISSUE THREAD

**Issue by kaarsenwinkel** [mollie/OpenCart#81]
Klanten krijgen erg vaak de betaling is verlopen, ik krijg dan eerst de betaling compleet binnen, en daarna de verlopen order, klanten denken dan vaak dat ze dubbel hebben betaald. Heb daar al een jaar last van, nu de laatste update van mollie geinstalleerd maar probleem blijft.
Ik gebruik opencart versie 2.3.0.2

**Comment by gh00per** [comment]
Heb ik ook last van, zeer lastig te achterhalen waar dit probleem vandaan komt.
Klanten geven soms aan betaald te hebben, terwijl het systeem bij ons aangeeft dat de betaling verlopen is - brengt soms verwarring bij ons en klant.
