### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by gh00per** [mollie/OpenCart#82]
Got this error out of nowhere, don't know what the problem could be. Already checked the conditions, and they are fine.

"Communicating with Mollie failed:
Unable to communicate with Mollie (6): Could not resolve host: api.mollie.nl; Name or service not known.

Please check the following conditions. You can ask your hosting provider to help with this.
Make sure outside connections to https://api.mollie.nl are not blocked.
Make sure SSL v3 is disabled on your server. Mollie does not support SSL v3.
Make sure your server is up-to-date and the latest security patches have been installed."

**Comment by wvdeutekom** [comment]
Thanks for reporting this. We're experiencing some DNS issues and are looking into this, we'll update once we know more.
