### ISSUE TITLE
Mollie Api Client v1 has updated cacert.pem

### ISSUE THREAD

**Issue by Smitsel** [mollie/OpenCart#83]
Hi,

We've updated the cacert.pem file in our v1 implementation of the api client.
The new v2 uses guzzle but for other plugins still using the v1 the pem file needs to be updated.

Can you update the v1 with the current state from this tree:
https://github.com/mollie/mollie-api-php/tree/v1-develop

And release it?

**Comment by willemstuursma** [comment]
@QualityWorks-Dev I've updated the Mollie API client by changing the included client to a git submodule. 

The submodule can easily be updated to newer versions now.

I've also updated the `release.sh` script to initialize the submodule and remove examples and tests which don't need to be part of the OpenCart package. 

Let me know what you think.
