### ISSUE TITLE
iDeal payment method not showing on checkout

### ISSUE THREAD

**Issue by snirp** [mollie/OpenCart#84]
Configuring a new OpenCart instance (3.0.2) with the most recent Mollie extension. I cannot get the iDeal payment method to show with the checkout. There is a valid Mollie account with API key and it is set for all goe-zones.
 
Any suggesting how to make the payment option appear or how to debug this?

**Comment by snirp** [comment]
BTW: also trying with test API key, but also no success.

**Comment by QualityWorks** [comment]
Can you double-check if all the order totals are set correctly? (Extensions > Extensions > order totals)

**Comment by snirp** [comment]
No, I did not even single check that. Apparently these were not migrated correctly in my upgrade, so I had to set them again. Works now after setting the order totals. Thx!
