### ISSUE TITLE
Engelse Payment status tekst door callback webhook

### ISSUE THREAD

**Issue by mangopavlova** [mollie/OpenCart#85]
De betreffende Opencart site is tweetalig. De default taal van de site is Engels. 
Volgend probleem treedt op:
Wanneer een klant in de NL taal een bestelling plaatst ontvangt deze een NL orderbevestiging. De status van de betaling wordt echter in het Engels weergegeven. De webhook callback lijkt de default taal van de site te selecteren.
Is hier een oplossing voor?
Opencart v2.1.0.3.
Mollie v6.4.1

**Comment by mangopavlova** [comment]
Bump

**Comment by mangopavlova** [comment]
Mollie Support?

**Comment by martinmollie** [comment]
Dank voor uw bericht en excuses voor de vertraging. Het probleem is doorgezet naar de ontwikkelaars van de plugin en zij zullen u spoedig verder helpen.

**Comment by mangopavlova** [comment]
Hallo, bedankt voor je reactie.

De callback triggert een bepaalde betaalstatus in opencart. Aan deze (numerieke) status zit een omschrijving vast die wordt weergegeven in de bestelling en in de bestelbevestigings email.

Normaliter moet de voor de omschrijving geselecteerde taal gelijk zijn aan de taal waarin de bestelling wordt geplaatst (ie. de taal die de klant heeft geselecteerd in OC).

Onze opencart installatie is 2-talig. Sinds de default taal van OC op engels staat zie ik dat de betaalstatus van een nederlandse bestelling weergegeven wordt met een engelse omschrijving.

De vraag is dus waarom de taal van de betaalstatus in de default systeemtaal plaats vindt en niet in de taal waarin de bestelling geplaatst wordt?

mvg,

On Jul 13, 2018 09:27, Quality Works <notifications@github.com> wrote:

kan je me uitleggen wat het probleem precies is? de status is engels, maar de rest van de mail nederlands? heb je de order statussen vertaald? In principe gebruikt de mollie module geen gebruik van eigen emails of statussen, alles komt uit de instellingen van de shop

**Comment by mangopavlova** [comment]
BUMP
Additionele info:

"Heb je de order statussen vertaald?"
-> Ja de site is 2-talig

"In principe gebruikt de mollie module geen gebruik van eigen emails of statussen, alles komt uit de instellingen van de shop"
-> Daar gaat het juist mis. De callback vanuit de mollie module die de betaalstatus doorgeeft doet dat op basis van de default systeemtaal en houdt dus geen rekening met de taal waarin de order geplaatst is.

Is er nog meer info nodig of is het probleem nu duidelijk?
