### ISSUE TITLE
Internal Error ?

### ISSUE THREAD

**Issue by domiiniic** [mollie/OpenCart#99]
OC version: 2.3.0.2
i got this error guys plz help me i tried everything:

[Thu Jul 19 16:35:06.869740 2018] [proxy_fcgi:error] [pid 98829:tid 140329961367296] [client 163.158.249.226:65042] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Error: Could not load model payment!' in /home/lilysmarktplaats.shop/public_html/system/storage/modification/system/engine/loader.php:169\nStack trace:\n#0 [internal function]: Loader->{closure}(Array, Array)\n#1 /home/lilysmarktplaats.shop/public_html/system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array)\n#2 /home/lilysmarktplaats.shop/public_html/catalog/controller/checkout/payment_method.php(53): Proxy->__call('getMethod', Array)\n#3 /home/lilysmarktplaats.shop/public_html/catalog/controller/checkout/payment_method.php(53): Proxy->getMethod(Array, 10.5875)\n#4 [internal function]: ControllerCheckoutPaymentMethod->index()\n#5 /home/lilysmarktplaats.shop/public_html/system/storage/modification/system/engine/action.php(51): call_user_func_array(Array, Array)\n#6 /home/lilysmarktplaats.shop/public_html/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))\n#7 [internal function]: ControllerStartupR...\n', referer: http://www.lilysmarktplaats.nl/index.php?route=checkout/checkout

I removed everything and upload everything allready for like 5 times.

I got the internal error while checking out at part 5.

**Comment by maximj** [comment]
Hi @domiiniic,

That error could be caused by a lot of different things. Can you e-mail us at info@qualityworks.eu with the admin and FTP credentials of the shop in question to allow us to further investigate this problem?

**Comment by QualityWorks-Dev** [comment]
Hi @domiiniic,

That error could be caused by a lot of different things. Can you e-mail us at info@qualityworks.eu with the admin and FTP credentials of the shop in question to allow us to further investigate this problem?

**Comment by domiiniic** [comment]
Dear,

I replied to the mail adress you guys gave me a few days ago. They didnt really knew what i was talking about, so i explained it to them what the problem was but didnt got any reply yet so far. Can i get a conformation that people ar looking at this problem ?

Kind regards, Dominic Kristelijn

Sent from my HTC

----- Reply message -----
